"""Unit tests for converter/generate_commands.py.

Covers the pieces that would silently produce wrong output:

- shorten_description: first-sentence cut, hard truncate, empty input
- render_command: frontmatter shape with/without argument-hint, body format
- collect_skills: fail-loud on missing name or dir/name mismatch
- write_commands: idempotent clean-and-rewrite of dist/commands/, one file per skill
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

CONVERTER_DIR = Path(__file__).resolve().parent.parent / "converter"
sys.path.insert(0, str(CONVERTER_DIR))

from generate_commands import (  # noqa: E402
    MAX_DESCRIPTION_LEN,
    collect_skills,
    render_command,
    shorten_description,
    write_commands,
)


# -------- shorten_description --------


def test_shorten_description_empty():
    assert shorten_description("") == ""


def test_shorten_description_short_passthrough():
    text = "Execute work efficiently while maintaining quality."
    assert shorten_description(text) == text


def test_shorten_description_first_sentence_cut():
    text = "Create a plan. Then iterate on it. Then commit."
    # First sentence ends at index 13 (". "), well under MAX_DESCRIPTION_LEN
    assert shorten_description(text) == "Create a plan."


def test_shorten_description_no_period_hard_truncate():
    text = "a" * 200
    out = shorten_description(text)
    assert len(out) == MAX_DESCRIPTION_LEN
    assert out.endswith("...")


def test_shorten_description_long_first_sentence_falls_through_to_truncate():
    # First sentence longer than MAX_DESCRIPTION_LEN — the period-cut shouldn't
    # fire (it only fires when period is within the cap). Truncate kicks in.
    text = "x" * 150 + ". another sentence."
    out = shorten_description(text)
    assert len(out) == MAX_DESCRIPTION_LEN
    assert out.endswith("...")


def test_shorten_description_collapses_whitespace():
    text = "Plan   tasks\n  with    structure."
    assert shorten_description(text) == "Plan tasks with structure."


# -------- render_command --------


def test_render_command_minimal_no_argument_hint():
    body = render_command("ce-plan", "Plan tasks with structure.", None)
    assert "description: \"Plan tasks with structure.\"" in body
    assert "argument-hint" not in body
    assert "Use the `ce-plan` skill" in body
    assert "$ARGUMENTS" in body
    assert "Generated by ce-lite converter" in body


def test_render_command_with_argument_hint():
    body = render_command(
        "ce-work",
        "Execute work.",
        "[Plan doc path or description of work]",
    )
    assert "description: \"Execute work.\"" in body
    assert "argument-hint: \"[Plan doc path or description of work]\"" in body
    assert "Use the `ce-work` skill" in body


def test_render_command_frontmatter_well_formed():
    body = render_command("ce-x", "desc", "hint")
    # Frontmatter fence shape: starts with --- on its own line, then keys, then ---
    lines = body.split("\n")
    assert lines[0] == "---"
    assert "description:" in lines[1]
    assert "argument-hint:" in lines[2]
    assert lines[3] == "---"


def test_render_command_handles_quotes_in_description():
    # JSON encoding handles embedded quotes safely
    body = render_command("ce-x", 'Run "the thing" carefully.', None)
    assert "description: \"Run \\\"the thing\\\" carefully.\"" in body


# -------- collect_skills --------


def _write_skill(skills_dir: Path, name: str, description: str, argument_hint: str | None = None) -> None:
    """Helper: create a minimal SKILL.md under skills_dir/<name>/."""
    skill_dir = skills_dir / name
    skill_dir.mkdir(parents=True)
    fm_lines = [f"name: {name}", f"description: {description!r}"]
    if argument_hint is not None:
        fm_lines.append(f"argument-hint: {argument_hint!r}")
    text = "---\n" + "\n".join(fm_lines) + "\n---\nbody\n"
    (skill_dir / "SKILL.md").write_text(text, encoding="utf-8")


def test_collect_skills_basic(tmp_path: Path):
    skills_dir = tmp_path / "skills"
    _write_skill(skills_dir, "ce-plan", "Plan tasks.", "[args]")
    _write_skill(skills_dir, "ce-work", "Execute work.")

    skills = collect_skills(tmp_path)
    names = {s[0] for s in skills}
    assert names == {"ce-plan", "ce-work"}

    # ce-plan has an argument-hint, ce-work doesn't
    by_name = {s[0]: s for s in skills}
    assert by_name["ce-plan"][2] == "[args]"
    assert by_name["ce-work"][2] is None


def test_collect_skills_fails_on_missing_skills_dir(tmp_path: Path):
    with pytest.raises(FileNotFoundError, match="skills"):
        collect_skills(tmp_path)


def test_collect_skills_fails_on_missing_name(tmp_path: Path):
    skills_dir = tmp_path / "skills" / "ce-broken"
    skills_dir.mkdir(parents=True)
    (skills_dir / "SKILL.md").write_text(
        "---\ndescription: 'no name field'\n---\nbody\n", encoding="utf-8"
    )
    with pytest.raises(ValueError, match="no 'name'"):
        collect_skills(tmp_path)


def test_collect_skills_fails_on_dir_name_mismatch(tmp_path: Path):
    skills_dir = tmp_path / "skills" / "wrong-dir"
    skills_dir.mkdir(parents=True)
    (skills_dir / "SKILL.md").write_text(
        "---\nname: ce-different\ndescription: 'mismatched'\n---\nbody\n",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="does not match"):
        collect_skills(tmp_path)


# -------- write_commands --------


def test_write_commands_creates_one_file_per_skill(tmp_path: Path):
    skills_dir = tmp_path / "skills"
    _write_skill(skills_dir, "ce-plan", "Plan tasks.", "[args]")
    _write_skill(skills_dir, "ce-work", "Execute work.")

    skills = collect_skills(tmp_path)
    written = write_commands(tmp_path, skills)

    commands_dir = tmp_path / "commands"
    assert commands_dir.is_dir()
    assert len(written) == 2
    assert (commands_dir / "ce-plan.md").is_file()
    assert (commands_dir / "ce-work.md").is_file()


def test_write_commands_is_idempotent(tmp_path: Path):
    skills_dir = tmp_path / "skills"
    _write_skill(skills_dir, "ce-plan", "Plan tasks.")
    skills = collect_skills(tmp_path)

    write_commands(tmp_path, skills)
    first = (tmp_path / "commands" / "ce-plan.md").read_text()

    write_commands(tmp_path, skills)
    second = (tmp_path / "commands" / "ce-plan.md").read_text()

    assert first == second


def test_write_commands_removes_stale_entries(tmp_path: Path):
    """Renames in dist/skills/ must propagate — stale command files get cleaned."""
    skills_dir = tmp_path / "skills"
    _write_skill(skills_dir, "ce-plan", "Plan tasks.")

    # Seed dist/commands/ with a stale entry that's no longer in dist/skills/
    commands_dir = tmp_path / "commands"
    commands_dir.mkdir()
    (commands_dir / "ce-deleted-skill.md").write_text("stale\n", encoding="utf-8")

    skills = collect_skills(tmp_path)
    write_commands(tmp_path, skills)

    assert (commands_dir / "ce-plan.md").is_file()
    assert not (commands_dir / "ce-deleted-skill.md").exists()


def test_write_commands_body_contains_skill_name(tmp_path: Path):
    skills_dir = tmp_path / "skills"
    _write_skill(skills_dir, "ce-debug", "Debug a failing test.", "[test name]")
    skills = collect_skills(tmp_path)
    write_commands(tmp_path, skills)

    body = (tmp_path / "commands" / "ce-debug.md").read_text()
    assert "ce-debug" in body
    assert "argument-hint: \"[test name]\"" in body
    assert "$ARGUMENTS" in body
