"""Generate slash-command wrappers for every skill in dist/skills/.

Why this stage exists: Claude Code auto-registers plugin-namespaced skill
entries in the slash-command autocomplete (e.g. `/ce-lite:ce-plan`), but
dispatch from those auto-registered entries is unreliable — autocomplete
shows the entry, submit doesn't always fire the underlying Skill. Plugins
that ship explicit `commands/<name>.md` files dispatch reliably because
slash commands from `commands/` are a first-class harness concept,
distinct from the skill-routing surface.

For each `dist/skills/<name>/SKILL.md`, this stage emits a thin
`dist/commands/<name>.md` whose body explicitly instructs the model to
invoke the matching skill with `$ARGUMENTS`. The skill body itself is
NOT duplicated — that would drift on every upstream bump and double the
disk footprint. The wrapper is ~10 lines.

Run order: after `generate_wrappers.py` (so the 49 persona wrappers + 2
meta-skills exist in dist/skills/) and before `validate.py` (which will
cross-check that every command maps to a skill and vice versa).
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

# Make extract importable when invoked as a script
sys.path.insert(0, str(Path(__file__).resolve().parent))

from extract import parse_frontmatter  # noqa: E402

COMMAND_GENERATED_MARKER = (
    "<!-- Generated by ce-lite converter — do not edit. "
    "Regenerate via converter/generate_commands.py. -->"
)

# Command-wrapper `description:` is the skill name itself (not the SKILL.md
# description blurb). Rationale: Claude Code counts each plugin-namespaced
# command (`/ce-lite:<name>`) as a separate skill entry in /context, with
# its own description-derived token cost — independent of the SKILL.md
# `description:` that drives the bare `/<name>` entry. Carrying the full
# blurb in both places double-charged ~6k tokens of idle context for ce-lite.
# The skill name alone is just enough to satisfy validate.py's non-empty
# check while collapsing the duplicate to ~5 tokens per command.


def render_command(skill_name: str, argument_hint: str | None) -> str:
    """Render the command-file body for one skill."""
    fm_lines = [
        f"description: {json.dumps(skill_name)}",
    ]
    if argument_hint:
        fm_lines.append(f"argument-hint: {json.dumps(argument_hint)}")
    frontmatter = "\n".join(fm_lines)

    return f"""\
---
{frontmatter}
---

{COMMAND_GENERATED_MARKER}

Use the `{skill_name}` skill (from the ce-lite plugin) to handle this request.

Arguments: $ARGUMENTS
"""


def collect_skills(dist: Path) -> list[tuple[str, str | None]]:
    """Return [(skill_name, argument_hint?), ...] for every SKILL.md.

    Fails loud if any SKILL.md has malformed frontmatter or no `name:` — the
    same skills will be expected to exist by validate.py, so silent skips
    would just push the failure to a less obvious place.
    """
    skills_dir = dist / "skills"
    if not skills_dir.is_dir():
        raise FileNotFoundError(f"missing {skills_dir}")

    out: list[tuple[str, str | None]] = []
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        text = skill_md.read_text(encoding="utf-8")
        try:
            fm, _ = parse_frontmatter(text)
        except ValueError as exc:
            raise ValueError(f"{skill_md}: {exc}") from exc
        name = fm.get("name")
        if not name:
            raise ValueError(f"{skill_md}: SKILL.md has no 'name' in frontmatter")
        # Sanity: skill dir name should match the SKILL.md name field
        if skill_md.parent.name != name:
            raise ValueError(
                f"{skill_md}: skill dir {skill_md.parent.name!r} does not match "
                f"frontmatter name {name!r}"
            )
        argument_hint = fm.get("argument-hint") or None
        out.append((name, argument_hint))
    return out


def write_commands(dist: Path, skills: list[tuple[str, str | None]]) -> list[Path]:
    commands_dir = dist / "commands"
    # Always start from a clean dir so renames in dist/skills/ propagate cleanly.
    if commands_dir.exists():
        shutil.rmtree(commands_dir)
    commands_dir.mkdir(parents=True)

    written: list[Path] = []
    for name, argument_hint in skills:
        body = render_command(name, argument_hint)
        out_path = commands_dir / f"{name}.md"
        out_path.write_text(body, encoding="utf-8")
        written.append(out_path)
    return written


def main(dist_arg: str) -> int:
    dist = Path(dist_arg).resolve()
    if not dist.is_dir():
        print(f"generate_commands.py: dist not found: {dist}", file=sys.stderr)
        return 2

    skills = collect_skills(dist)
    written = write_commands(dist, skills)

    print(
        f"generate_commands.py: wrote {len(written)} command wrappers "
        f"to {dist / 'commands'}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("dist", help="path to converted plugin dist/ directory")
    args = parser.parse_args()
    sys.exit(main(args.dist))
