"""Generate per-persona wrapper skills (Tier 3) + bin/ce-lite-persona resolver.

Each entry in `dist/references/agent-prompts/manifest.json` becomes a thin
SKILL.md at `dist/skills/ce-ask-<persona>/SKILL.md`. The wrapper restores
addressability through Claude's skill-routing surface — Claude can
spontaneously suggest `/ce-ask-security-sentinel` when reviewing
security-sensitive code, without re-paying the persistent-agent
registration cost (49 agents × ~1.2k tokens = ~58.8k baseline that the
ce-lite v1 converter strips).

Dispatch lookup is handled by a single small Python shim at
`dist/bin/ce-lite-persona` (this directory is on PATH because Claude Code
exports installed-plugin `bin/`). Wrapper SKILL.md bodies — and the
orchestrator dispatch-protocol preamble injected by `rewrite.py` — just
invoke `ce-lite-persona <name> --body` instead of carrying ~500 tokens of
Glob/find discovery scaffolding each. Net: same idle cost (~22 tok per
wrapper-skill description), lower per-dispatch context cost.

Naming convention: `ce-ask-<persona-bare-name>`. The `ce-` prefix is
stripped from the agent name before re-prefixing with `ce-ask-` so we
get `ce-ask-security-sentinel` rather than `ce-ask-ce-security-sentinel`.
The canonical persona name (`ce-security-sentinel`) stays referenced in
the wrapper body — that's what gets dispatched to the persona prompt
file. Naming this way keeps the canonical names available for a future
Tier 4 (lazy agent registration) re-registration without a name fight.

Description generation is two-pass:

  - Pass A (this script, deterministic): strip the "Conditional X persona,
    selected when..." agent-routing preamble where present; otherwise pass
    the manifest description through unchanged. Cheap baseline.
  - Pass B (run separately, locally, before each release): drive
    `document-skills:skill-creator`'s `improve_description.py` over the
    full set; commit refined descriptions to overrides/persona-descriptions.yaml;
    re-run this generator with overrides applied. Not a CI step (no LLM
    in CI invariant from the parent converter plan).

If `overrides/persona-descriptions.yaml` exists in the converter repo
(sibling to this script), per-persona overrides take precedence over
Pass A output.

The wrapper template embeds:

  1. A "do not edit" marker so round-trip cleanup can identify generated
     files and Tier 4 migration knows what to delete.
  2. A `[ce-persona=<n> via=ce-ask-direct]` trace tag for inline
     debugging (grep transcripts when a routing question comes up; not
     systematic usage data collection).
  3. A tool-restriction self-policing preamble that turns the manifest's
     advisory `tools:` field into loud-advisory inside the dispatched
     prompt (the harness can't enforce because we dispatch via
     general-purpose, but the agent can self-police if explicitly told).
  4. An `Agent.description` template — meaningful labels on the dispatch
     so traces don't read as anonymous "general-purpose" runs.
  5. The canonical persona name in the body (never the wrapper name) so
     Tier 4 migration is a mechanical s/// over wrapper-bodies.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

CONDITIONAL_PREFIX_RE = re.compile(
    r"^Conditional\s+[a-z][a-z\-/]*\s+persona,\s+selected\s+when\s+",
    re.IGNORECASE,
)

WRAPPER_GENERATED_MARKER = (
    "<!-- Generated by ce-lite converter — do not edit. "
    "Regenerate via converter/generate_wrappers.py. -->"
)


# Persona prompts live inside this plugin's install dir. Rather than embed
# Glob/find discovery scaffolding in every wrapper SKILL.md body (~500 tok
# of repeated scaffolding per skill), we ship a `bin/ce-lite-persona`
# resolver. Claude Code exports each installed plugin's `bin/` onto PATH, so
# dispatch sites can invoke `ce-lite-persona <name> --body` directly in one
# Bash call. The resolver itself walks up from its own location (or honours
# $CLAUDE_PLUGIN_ROOT) to find the plugin root; the SKILL.md author doesn't
# need to know the install path.


@dataclass(frozen=True)
class Persona:
    name: str
    description: str
    model: str
    tools: list[str] | None
    prompt_path: str


def load_manifest(dist: Path) -> list[Persona]:
    manifest_path = dist / "references" / "agent-prompts" / "manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"missing manifest: {manifest_path}")
    raw = json.loads(manifest_path.read_text(encoding="utf-8"))
    return [
        Persona(
            name=a["name"],
            description=a["description"],
            model=a.get("model") or "inherit",
            tools=a.get("tools"),
            prompt_path=a["prompt_path"],
        )
        for a in raw["agents"]
    ]


def load_overrides(converter_dir: Path) -> dict[str, str]:
    """Load overrides/persona-descriptions.yaml as a flat name→description map.

    Format (light-touch YAML, no nesting):

        ce-security-sentinel: |
          Use when reviewing for security issues...
        ce-architecture-strategist: "Use when ..."

    Empty file or missing file returns {}. Keep the parser deliberately
    minimal — overrides are populated by skill-creator and committed to
    the repo, not edited at scale by hand.
    """
    overrides_path = converter_dir / "overrides" / "persona-descriptions.yaml"
    if not overrides_path.is_file():
        return {}
    text = overrides_path.read_text(encoding="utf-8")
    result: dict[str, str] = {}
    current_key: str | None = None
    current_val: list[str] = []
    block_indent: int | None = None
    for raw_line in text.splitlines():
        # Skip pure comments / blank lines at top level.
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            if current_key is None:
                continue
        # Top-level key (no leading whitespace, has colon).
        if raw_line and not raw_line[0].isspace() and ":" in raw_line:
            # Flush previous key.
            if current_key is not None:
                result[current_key] = "\n".join(current_val).rstrip()
                current_val = []
                block_indent = None
            key, _, value = raw_line.partition(":")
            current_key = key.strip()
            value = value.strip()
            if value in ("|", ">", "|-", ">-"):
                # Block scalar follows on indented lines.
                continue
            if value:
                # Inline scalar; strip optional quotes.
                if (value.startswith('"') and value.endswith('"')) or (
                    value.startswith("'") and value.endswith("'")
                ):
                    value = value[1:-1]
                result[current_key] = value
                current_key = None
                current_val = []
                block_indent = None
            continue
        # Indented continuation of a block scalar.
        if current_key is not None and raw_line and raw_line[0].isspace():
            # Establish block indent on first content line.
            indent = len(raw_line) - len(raw_line.lstrip())
            if block_indent is None:
                block_indent = indent
            # Strip the common indent.
            current_val.append(raw_line[block_indent:])
    if current_key is not None:
        result[current_key] = "\n".join(current_val).rstrip()
    return result


def wrapper_name(persona_name: str) -> str:
    """ce-security-sentinel → ce-ask-security-sentinel."""
    if persona_name.startswith("ce-"):
        return f"ce-ask-{persona_name[3:]}"
    return f"ce-ask-{persona_name}"


def passA_description(manifest_desc: str) -> str:
    """Strip the agent-routing 'Conditional X, selected when...' preamble.

    Most upstream descriptions are already action-oriented; only the
    'Conditional' family of personas reads as agent-routing language and
    benefits from rewriting. Pass through unchanged otherwise — Pass B
    (skill-creator-driven) will tune the rest.
    """
    if CONDITIONAL_PREFIX_RE.match(manifest_desc):
        rest = CONDITIONAL_PREFIX_RE.sub("", manifest_desc, count=1)
        return f"Use when {rest}"
    return manifest_desc


def render_wrapper(persona: Persona, description: str) -> str:
    return f"""\
---
name: {wrapper_name(persona.name)}
description: {json.dumps(description)}
---

{WRAPPER_GENERATED_MARKER}

Dispatch the **{persona.name}** specialist as a sub-agent.

1. Run `ce-lite-persona {persona.name} --prefix` via Bash. Output is the
   full prompt prefix — persona body, `[ce-persona={persona.name} via=ce-ask-direct]`
   trace tag, and the tool-restriction self-policing preamble derived from the
   manifest — ready to concatenate with the task. Non-zero exit means the
   resolver hit an error (unknown persona, missing prompt file, partial
   install); surface stderr and stop without falling back.

2. Spawn `Agent` with `subagent_type: "general-purpose"` and
   `description: "{persona.name}: <one-line task summary>"` so traces stay
   readable. `prompt` is the resolver's stdout from step 1, a blank line,
   then `$ARGUMENTS`. The task is never passed through Bash on the resolver
   call — concatenate it into the Agent.prompt parameter directly.

For parallel multi-persona dispatch, see `/ce-ask-panel`.
"""


def write_wrapper(dist: Path, persona: Persona, description: str) -> Path:
    skill_dir = dist / "skills" / wrapper_name(persona.name)
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(render_wrapper(persona, description), encoding="utf-8")
    return skill_path


PANEL_DESCRIPTION = (
    "Use to consult several persona specialists in parallel and merge their "
    "findings into one response. Provide a comma-separated list of persona "
    "names plus the task context. Bridges single-persona reach (one ce-ask-* "
    "skill) and full orchestrator pipelines (ce-code-review etc.) when you "
    "want N specific perspectives but not the full review pipeline."
)


def render_panel(personas: list[Persona]) -> str:
    """Render the ce-ask-panel meta-skill body.

    Static template — same regardless of which personas exist; the runtime
    validates against the live manifest via the ce-lite-persona resolver.
    Listing personas at generation time would force regeneration on every
    upstream tag bump just to update a list Claude can read from
    manifest.json directly.
    """
    return f"""\
---
name: ce-ask-panel
description: {json.dumps(PANEL_DESCRIPTION)}
argument-hint: "<persona1>,<persona2>,... <task context>"
---

{WRAPPER_GENERATED_MARKER}

Dispatch a panel of multiple persona specialists in parallel and merge their
findings into one response. Bridges single-persona ad-hoc reach
(`/ce-ask-<one-persona>`) and the full orchestrator pipelines
(`/ce-code-review`, `/ce-doc-review`, `/ce-resolve-pr-feedback`) — use this
when you want N specific perspectives without the rest of the pipeline.

## Usage

`/ce-ask-panel <persona1>,<persona2>,... <task context>`

Persona names are the **canonical** names from the plugin's persona manifest
(e.g. `ce-security-sentinel`, `ce-architecture-strategist`), NOT the
`ce-ask-*` wrapper names.

## Steps

1. Parse the first whitespace-delimited token as a comma-separated persona
   list (trim each name). Treat the rest as the user's task context.

2. Validate each persona by running `ce-lite-persona <name> --path` via
   Bash. Non-zero exit means an unknown persona — the resolver's stderr
   lists all known personas. Surface that to the user and stop without
   dispatching anything; partial dispatches confuse merged output.

3. For each validated persona, dispatch in parallel via `Agent` with
   `subagent_type: "general-purpose"` and
   `description: "<persona>: <task summary>"` (meaningful trace label).
   The prompt is the output of
   `ce-lite-persona <persona> --prefix --via ce-ask-panel`, a blank line,
   then the user-supplied task context. The task is concatenated into the
   Agent.prompt parameter directly — not passed to the resolver.

4. Wait for all dispatches to complete. Merge into one response, grouping
   by persona with section headers (`## <persona> findings`). Preserve each
   persona's structured output — don't collapse into prose.

## Notes

- Trace tag `via=ce-ask-panel` distinguishes panel dispatch from direct
  invocation (`via=ce-ask-direct`) when grepping transcripts.
- For one persona, prefer `/ce-ask-<persona-bare-name>` — cheaper than
  going through the panel parser.
- For full-pipeline reviews, prefer the orchestrator skills
  (`/ce-code-review`, `/ce-doc-review`) which include conditional persona
  selection.
"""


def write_panel(dist: Path, personas: list[Persona]) -> Path:
    skill_dir = dist / "skills" / "ce-ask-panel"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(render_panel(personas), encoding="utf-8")
    return skill_path


META_SKILL_DESCRIPTION = (
    "Discover and dispatch ce-lite specialist personas via a single slash command. "
    "Run with no args to browse the persona catalog (security, architecture, "
    "correctness, simplicity, pattern, performance, data-integrity, doc review, "
    "and more). Run with `<persona-name>` to see one persona's role. Run with "
    "`<persona-name> <task>` to dispatch that specialist on the task. For "
    "tab-complete-friendly invocation use `/ce-ask-<persona>` directly; for "
    "parallel multi-persona dispatch use `/ce-ask-panel`."
)


DEFAULT_HOOK_RULES = {
    "config": {
        "haiku_classifier": {
            "enabled": False,
            "model": "haiku",
            "max_budget_usd": 0.005,
            "timeout_seconds": 8,
            "min_confidence": 0.6,
            "_doc": (
                "Optional Haiku-based intent classifier. When enabled, the "
                "hook falls back to a Haiku call if keyword matching produces "
                "no hit. Haiku reads the user prompt + persona catalog and "
                "returns a structured suggestion. Adds ~1–2s latency per "
                "non-keyword-matching prompt and ~$0.001 quota each. Set "
                "enabled=true to opt in. The keyword path always runs first "
                "(cheap and deterministic); Haiku is the no-keyword "
                "fallback only."
            ),
        }
    },
    "rules": [
        {
            "keywords": [
                "security", "vuln", "vulnerab", "OWASP", "injection", "XSS",
                "CSRF", "SSRF", "auth ", "auth-", "JWT", "OAuth",
                "mass assignment", "sanitiz", "hardcoded secret", "credential leak",
                "open redirect", "deserialization", "is this safe",
                "paranoid review", "is it safe to ship", "before we ship",
            ],
            "persona": "ce-security-sentinel",
            "phrasing": (
                "The prompt looks security-flavored. Consider running "
                "`/ce-lite:ce-ask-security-sentinel` (or invoking the wrapper "
                "via Skill) for a focused security review by a specialist "
                "persona. The wrapper dispatches a sub-agent grounded in "
                "OWASP / injection / authn-authz / secrets-handling expertise."
            ),
        },
        {
            "keywords": [
                "factor out", "extract method", "extract class", "duplicat",
                "copy-pasted", "DRY", "coupling", "abstraction", "boundaries",
                "structural refactor", "service boundaries", "module bound",
                "pattern compliance", "design integrity",
            ],
            "persona": "ce-architecture-strategist",
            "phrasing": (
                "Architecture/design concerns visible. Consider "
                "`/ce-lite:ce-ask-architecture-strategist` for a structural "
                "review (pattern compliance, layer violations, naming "
                "consistency)."
            ),
        },
        {
            "keywords": [
                "YAGNI", "over-engineered", "premature abstraction",
                "redundant abstraction", "simplify", "simpler way",
                "is this too clever", "unnecessary indirection",
                "feels overcomplicated", "could this be simpler",
            ],
            "persona": "ce-code-simplicity-reviewer",
            "phrasing": (
                "Simplicity concerns visible. Consider "
                "`/ce-lite:ce-ask-code-simplicity-reviewer` for a YAGNI/"
                "redundancy review."
            ),
        },
        {
            "keywords": [
                "edge case", "off-by-one", "race condition", "deadlock",
                "concurrency bug", "correctness", "logic bug",
                "is this correct", "boundary condition",
            ],
            "persona": "ce-correctness-reviewer",
            "phrasing": (
                "Correctness concerns visible. Consider "
                "`/ce-lite:ce-ask-correctness-reviewer` for an edge-case / "
                "boundary-condition review."
            ),
        },
        {
            "keywords": [
                "naming consistency", "convention drift", "style consistency",
                "naming pattern", "matches existing", "consistent with",
                "follow the pattern",
            ],
            "persona": "ce-pattern-recognition-specialist",
            "phrasing": (
                "Pattern/consistency review may help. Consider "
                "`/ce-lite:ce-ask-pattern-recognition-specialist` to surface "
                "duplication and convention drift."
            ),
        },
        {
            "keywords": [
                "performance", "latency", "bottleneck", "slow query",
                "N+1", "p99", "throughput", "memory pressure",
            ],
            "persona": "ce-performance-oracle",
            "phrasing": (
                "Performance angle visible. Consider "
                "`/ce-lite:ce-ask-performance-oracle` for a structured "
                "performance review."
            ),
        },
    ]
}


def render_meta_skill() -> str:
    """Render the /ce-ask single-slash-command catalog/dispatch surface.

    Catalog is read from manifest.json at runtime — body stays stable across
    upstream tag bumps even when persona list changes. Per-persona wrappers
    (/ce-ask-<persona>) provide tab-complete-friendly explicit invocation; this
    meta-skill provides the discoverable single-command surface for users who
    don't have a specific persona name in mind yet.
    """
    return f"""\
---
name: ce-ask
description: {json.dumps(META_SKILL_DESCRIPTION)}
argument-hint: "[persona-name [task context]]"
---

{WRAPPER_GENERATED_MARKER}

Single discoverable entry point to ce-lite specialist personas. Three modes
based on argument shape.

## Usage

- `/ce-ask` — print the persona catalog (name + specialty for each).
- `/ce-ask <persona>` — show one persona's full role definition.
- `/ce-ask <persona> <task>` — dispatch that persona on the task.

Persona names are the canonical names from the manifest (e.g.
`ce-security-sentinel`). Argument parsing: first whitespace-delimited token
is the persona name; everything after is the task context.

## Steps

1. **No args** — run `ce-lite-persona --list` via Bash and present the
   output (one persona per line, `<name><TAB><description>`). The resolver
   reads the manifest at runtime; no regeneration is needed when upstream
   adds or removes personas. Stop.

2. **Persona name only** — run `ce-lite-persona <name> --body` and present
   the role definition. Non-zero exit means an unknown persona; surface the
   resolver's stderr (it lists known names) and stop.

3. **Persona name + task** — dispatch via `Agent` with
   `subagent_type: "general-purpose"` and
   `description: "<persona>: <task summary>"` (meaningful trace label).
   The prompt is the output of
   `ce-lite-persona <persona> --prefix --via ce-ask-meta`, a blank line,
   then the user task. The task is concatenated into the Agent.prompt
   parameter directly — not passed to the resolver.

## Notes

- Tab-complete-friendly explicit invocation: `/ce-ask-<persona-name>` (one
  per persona).
- Parallel multi-persona dispatch: `/ce-ask-panel <a>,<b>,<c> <task>`.
- The catalog is read from `manifest.json` at runtime via the resolver, so
  this skill body doesn't need regeneration when the persona list changes.
"""


def write_meta_skill(dist: Path) -> Path:
    skill_dir = dist / "skills" / "ce-ask"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(render_meta_skill(), encoding="utf-8")
    return skill_path


# ---- bin/ce-lite-persona resolver shim ----
#
# Skills can't enumerate the plugin install path declaratively. Claude Code
# exports each installed plugin's `bin/` onto PATH, so we ship a tiny stdlib-
# only Python script there: SKILL.md bodies just call
# `ce-lite-persona <name> --body` in one Bash invocation instead of carrying
# Glob/find scaffolding. The resolver walks up from its own location (or
# honours $CLAUDE_PLUGIN_ROOT, which is set in hook subprocesses) to find
# the plugin root, validates against manifest.json, and prints the prompt
# path or body. Errors land on stderr with non-zero exit and a one-line
# `ce-lite-persona: <reason>` prefix.


def render_persona_resolver() -> str:
    """Emit dist/bin/ce-lite-persona — the dispatch resolver shim."""
    return '''#!/usr/bin/env python3
"""ce-lite-persona — resolve a persona name to its prompt file or body.

Generated by ce-lite converter (converter/generate_wrappers.py).
Don't edit; regenerate from the converter.

The plugin's `bin/` is on PATH because Claude Code exports it for installed
plugins, so dispatch sites in skill bodies invoke this directly:

    ce-lite-persona ce-security-sentinel --prefix [--via ce-code-review]
                                                  # full prompt prefix:
                                                  # body + trace tag +
                                                  # tool-restriction preamble.
                                                  # Concatenate with the task
                                                  # to form Agent.prompt.
    ce-lite-persona ce-security-sentinel --body   # bare prompt body only
    ce-lite-persona ce-security-sentinel --path   # absolute path
    ce-lite-persona --list                        # tab-separated catalog
    ce-lite-persona --diagnose                    # install health check

Plugin-root resolution order:
  1. $CLAUDE_PLUGIN_ROOT if set and contains .claude-plugin/plugin.json.
  2. Walk up from this script's resolved location.

Persona names accept the canonical form (`ce-security-sentinel`) or the
bare form (`security-sentinel`).

The task content NEVER passes through argv on a --prefix call — only the
persona name and dispatch source do. Arbitrary user task content (quotes,
backticks, dollar signs, newlines) is safe because the caller concatenates
the resolver's stdout with the task inside the Agent.prompt JSON parameter,
which bash never sees.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


def find_plugin_root() -> Path:
    env_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env_root:
        root = Path(env_root)
        if (root / ".claude-plugin" / "plugin.json").is_file():
            return root
    here = Path(__file__).resolve().parent
    for cand in [here, *here.parents]:
        if (cand / ".claude-plugin" / "plugin.json").is_file():
            return cand
    sys.exit(
        "ce-lite-persona: could not locate plugin root "
        "(checked $CLAUDE_PLUGIN_ROOT and parents of this script). "
        "Plugin may not be fully installed."
    )


def load_manifest(root: Path) -> dict:
    path = root / "references" / "agent-prompts" / "manifest.json"
    if not path.is_file():
        sys.exit(f"ce-lite-persona: missing manifest at {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        sys.exit(f"ce-lite-persona: malformed manifest at {path}: {exc}")


def canonicalize(name: str) -> str:
    return name if name.startswith("ce-") else f"ce-{name}"


def find_persona(manifest: dict, name: str) -> dict:
    canonical = canonicalize(name)
    for agent in manifest.get("agents", []):
        if agent.get("name") == canonical:
            return agent
    known = ", ".join(sorted(a["name"] for a in manifest.get("agents", [])))
    sys.exit(
        f"ce-lite-persona: unknown persona '{name}'. "
        f"Known personas: {known}"
    )


def cmd_path(root: Path, persona: dict) -> int:
    path = root / persona["prompt_path"]
    if not path.is_file():
        sys.exit(
            f"ce-lite-persona: prompt file missing: {path} "
            f"(manifest declares it; partial install?)"
        )
    print(path)
    return 0


def cmd_body(root: Path, persona: dict) -> int:
    path = root / persona["prompt_path"]
    if not path.is_file():
        sys.exit(f"ce-lite-persona: prompt file missing: {path}")
    sys.stdout.write(path.read_text(encoding="utf-8"))
    return 0


# Recognised dispatch sources for --via. Anything outside this set is rejected
# (typo defence). Keep this list in sync with the wrapper templates that pass
# --via and the generated meta-skill/panel/orchestrator preambles.
DISPATCH_SOURCES = {
    "ce-ask-direct",   # /ce-ask-<persona> wrapper
    "ce-ask-meta",     # /ce-ask <persona> ...
    "ce-ask-panel",    # /ce-ask-panel a,b,c ...
    "ce-code-review",
    "ce-doc-review",
    "ce-resolve-pr-feedback",
}


def cmd_prefix(root: Path, persona: dict, via: str) -> int:
    """Emit the full dispatch prompt prefix: body + trace tag + tool restriction.

    Concatenate this with the user task to form the Agent.prompt parameter.
    The task never touches argv here (and never touches Bash either when the
    caller does it via the Agent tool's structured parameter), so there is no
    shell-quoting risk for arbitrary task content.
    """
    if via not in DISPATCH_SOURCES:
        sys.exit(
            f"ce-lite-persona: unknown --via dispatch source: '{via}'. "
            f"Known sources: {', '.join(sorted(DISPATCH_SOURCES))}"
        )
    path = root / persona["prompt_path"]
    if not path.is_file():
        sys.exit(f"ce-lite-persona: prompt file missing: {path}")

    body = path.read_text(encoding="utf-8").rstrip("\\n")
    tools = persona.get("tools") or []
    tools_str = ", ".join(tools) if tools else "any"
    model = persona.get("model") or "inherit"
    name = persona["name"]

    preamble = (
        f"[ce-persona={name} via={via}]\\n"
        f"\\n"
        f"You are operating as the {name} specialist. Manifest declares this "
        f"role uses tools=[{tools_str}] and model={model}. Honour those "
        f"constraints: if a task pulls you toward tools outside that set, "
        f"stop and explain why your role requires it — don't silently broaden "
        f"scope.\\n"
    )

    sys.stdout.write(body + "\\n\\n" + preamble)
    return 0


def cmd_list(manifest: dict) -> int:
    for agent in manifest.get("agents", []):
        desc = (agent.get("description", "") or "").splitlines()
        first_line = desc[0] if desc else ""
        sys.stdout.write(f"{agent['name']}\\t{first_line}\\n")
    return 0


def cmd_diagnose(root: Path, manifest: dict) -> int:
    sys.stdout.write(f"plugin_root: {root}\\n")
    sys.stdout.write(
        f"manifest:    {root / 'references' / 'agent-prompts' / 'manifest.json'}\\n"
    )
    sys.stdout.write(f"personas:    {len(manifest.get('agents', []))}\\n")
    missing = [
        a["name"] for a in manifest.get("agents", [])
        if not (root / a["prompt_path"]).is_file()
    ]
    if missing:
        sys.stderr.write(
            f"ce-lite-persona: missing prompt files for: {', '.join(missing)}\\n"
        )
        return 1
    sys.stdout.write("status:      ok\\n")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="ce-lite-persona",
        description=(
            "Resolve a ce-lite persona name to its prompt file path or body. "
            "Invoked from generated SKILL.md dispatch sites and orchestrator "
            "preambles to avoid the per-dispatch glob/find dance."
        ),
    )
    parser.add_argument(
        "persona", nargs="?",
        help="canonical (ce-security-sentinel) or bare (security-sentinel) name",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--path", action="store_true",
        help="print absolute path to the persona's prompt file",
    )
    group.add_argument(
        "--body", action="store_true",
        help="cat the prompt file contents to stdout (default)",
    )
    group.add_argument(
        "--prefix", action="store_true",
        help=(
            "emit the full dispatch prompt prefix (body + trace tag + "
            "tool-restriction preamble), ready to concatenate with the task. "
            "Use with --via to record the dispatch source in the trace tag."
        ),
    )
    group.add_argument(
        "--list", action="store_true", dest="list_all",
        help="list all available personas (name<TAB>description)",
    )
    group.add_argument(
        "--diagnose", action="store_true",
        help="print plugin root, manifest path, and per-persona prompt presence",
    )
    parser.add_argument(
        "--via", default="ce-ask-direct",
        help=(
            "dispatch source recorded in the [ce-persona=NAME via=SOURCE] "
            "trace tag emitted by --prefix. Defaults to ce-ask-direct."
        ),
    )
    args = parser.parse_args(argv)

    root = find_plugin_root()
    manifest = load_manifest(root)

    if args.list_all:
        return cmd_list(manifest)
    if args.diagnose:
        return cmd_diagnose(root, manifest)
    if not args.persona:
        parser.error(
            "persona name required unless --list or --diagnose is given"
        )
    persona = find_persona(manifest, args.persona)
    if args.path:
        return cmd_path(root, persona)
    if args.prefix:
        return cmd_prefix(root, persona, args.via)
    return cmd_body(root, persona)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
'''


def write_persona_resolver(dist: Path) -> Path:
    """Emit dist/bin/ce-lite-persona, executable."""
    bin_dir = dist / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    resolver_path = bin_dir / "ce-lite-persona"
    resolver_path.write_text(render_persona_resolver(), encoding="utf-8")
    resolver_path.chmod(0o755)
    return resolver_path


# ---- UserPromptSubmit hook (Phase B.7) ----
#
# Phase B.5's meta-agent (ce-specialist) didn't fire autonomously — the
# integration eval (Phase B.6) measured 0/2 on autonomous review prompts even
# with the agent registered and visible to claude -p. Industry-wide
# research (scottspence.com, paddo.dev, jefflester/claude-skills-supercharged,
# spences10/claude-skills-cli) converges on the same finding: skills/agents
# auto-activate ~20% of the time even with good descriptions, because Claude
# defaults to handling tasks itself rather than delegating to specialists.
#
# The proven workaround is a UserPromptSubmit hook that detects review-flavored
# keywords and injects a suggestion ("consider /ce-ask-<persona>") into the
# prompt before Claude sees it. Measured activation rates jump to 70–84% with
# this approach. Cost is per-matching-prompt (a few hundred tokens of
# injected suggestion), zero at idle — much cheaper than a registered agent
# (~2k always-on) for occasional users.
#
# References:
#   https://scottspence.com/posts/claude-code-skills-dont-auto-activate
#   https://paddo.dev/blog/claude-skills-hooks-solution/
#   https://github.com/anthropics/claude-code/issues/9716


def render_hook_config() -> str:
    """Emit dist/hooks/hooks.json — Claude Code's hook declaration spec."""
    return json.dumps({
        "description": (
            "ce-lite UserPromptSubmit hook: detect review-flavored prompts and "
            "suggest invoking the matching specialist persona wrapper. Pure "
            "keyword matching; no LLM call per prompt; no idle-context cost."
        ),
        "hooks": {
            "UserPromptSubmit": [
                {
                    "hooks": [
                        {
                            "type": "command",
                            "command": "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/auto_suggest.py",
                            "timeout": 5,
                        }
                    ]
                }
            ]
        },
    }, indent=2) + "\n"


def render_hook_rules() -> str:
    """Emit dist/hooks/skill-rules.json — keyword → persona suggestion table.

    This file is the curated extension point. Each release of the converter
    can ship updated default rules; downstream users can override by replacing
    skill-rules.json with their own (any plugin-cache rebuild from upstream
    overwrites it, so persistent customisation should live in a separate
    user-level hook). Keywords are case-insensitive substring matches.
    """
    return json.dumps(DEFAULT_HOOK_RULES, indent=2) + "\n"


def render_hook_script() -> str:
    """Emit dist/hooks/auto_suggest.py — the actual hook implementation.

    Runs once per user prompt. Reads UserPromptSubmit JSON payload from stdin
    (Claude Code hook protocol); matches `prompt` text against
    skill-rules.json keywords (case-insensitive substring); emits an
    `additionalContext` JSON response that gets prepended to Claude's view of
    the prompt. No match → silent exit (zero token cost). At most 3 personas
    suggested per prompt (avoid noise).

    Standard library only — no PyYAML / pyyaml dependency. Fast cold-start
    (~30 ms python overhead + microseconds of matching).
    """
    return '''#!/usr/bin/env python3
"""ce-lite UserPromptSubmit hook — suggest specialist personas based on prompt content.

Generated by ce-lite converter (converter/generate_wrappers.py). Don't edit;
regenerate from `skill-rules.json` instead — this script only loads rules
and config from there at runtime.

Protocol: Claude Code passes the user's prompt as JSON on stdin. If a
suggestion is warranted, we emit `{"hookSpecificOutput": {"hookEventName":
"UserPromptSubmit", "additionalContext": "..."}}` on stdout — that text gets
injected into Claude's view of the prompt as a system reminder before Claude
responds. Silent exit (no stdout) if nothing matches.

Two suggestion strategies:

  1. Keyword matching (default, always runs first). Substring-matches the
     prompt against rule keywords. Cheap, deterministic, no API cost.

  2. Haiku intent classifier (opt-in via config.haiku_classifier.enabled).
     If keyword matching produces no hit AND Haiku is enabled, runs
     `claude -p --model haiku --json-schema` to classify the prompt's intent
     against the persona catalog. ~1-2s latency, ~$0.001 quota per
     no-keyword-match prompt. Per ~/.claude/memory/claude_p_headless_subscription.md
     we use the lightweight invocation pattern (--system-prompt,
     --setting-sources "", CLAUDE_CODE_DISABLE_*).

Reference: https://code.claude.com/docs/en/hooks
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

_GENERATED_BY = "ce-lite converter"

RULES_PATH = Path(__file__).parent / "skill-rules.json"
MAX_SUGGESTIONS = 3  # cap injected text length on prompts that match many rules


def _load_config_and_rules() -> tuple[dict, list[dict]]:
    if not RULES_PATH.is_file():
        return {}, []
    try:
        data = json.loads(RULES_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}, []
    if not isinstance(data, dict):
        return {}, []
    config = data.get("config") if isinstance(data.get("config"), dict) else {}
    rules = data.get("rules") if isinstance(data.get("rules"), list) else []
    return config, rules


def _matches(prompt_lower: str, keywords: list[str]) -> bool:
    return any(
        isinstance(kw, str) and kw.lower() in prompt_lower
        for kw in keywords
    )


def _keyword_suggestions(rules: list[dict], prompt_lower: str) -> list[dict]:
    """Return the matching rules (in declaration order, capped at MAX_SUGGESTIONS)."""
    matched: list[dict] = []
    for rule in rules:
        if not isinstance(rule, dict):
            continue
        keywords = rule.get("keywords") or []
        if _matches(prompt_lower, keywords):
            matched.append(rule)
        if len(matched) >= MAX_SUGGESTIONS:
            break
    return matched


def _haiku_classify(prompt: str, rules: list[dict], cfg: dict) -> dict | None:
    """Optional fallback: run Haiku via `claude -p` to suggest a persona.

    Returns a synthetic rule-shaped dict (with `persona` and `phrasing`) if
    Haiku returns a confident classification. Returns None on any failure
    (network, quota, malformed output, low confidence) — caller treats
    that as "no suggestion."

    Uses the lightweight subscription-quota invocation pattern: minimal
    system prompt, no auto-memory, no settings hierarchy, JSON-schema
    constrained output, hard budget cap. See
    ~/.claude/memory/claude_p_headless_subscription.md.
    """
    if not cfg.get("enabled"):
        return None
    claude_bin = shutil.which("claude")
    if not claude_bin:
        return None

    catalog_lines = []
    for rule in rules:
        if not isinstance(rule, dict):
            continue
        persona = rule.get("persona")
        if persona:
            keywords = rule.get("keywords") or []
            kw_summary = ", ".join(keywords[:6])
            catalog_lines.append(f"- {persona}: {kw_summary}")
    if not catalog_lines:
        return None
    catalog = "\\n".join(catalog_lines)

    system = (
        "You are a routing classifier for ce-lite specialist personas. The "
        "user submitted a prompt to a coding assistant. Decide if any "
        "specialist persona below would substantively improve the response "
        "(by providing focused expertise the main agent might miss). Return "
        "one persona name with a confidence 0.0-1.0, OR null if no "
        "specialist clearly fits.\\n\\nAvailable personas (name: keywords):\\n"
        + catalog
    )
    schema = {
        "type": "object",
        "properties": {
            "persona": {"type": ["string", "null"]},
            "confidence": {"type": "number"},
            "reason": {"type": "string"},
        },
        "required": ["persona", "confidence"],
    }

    cmd = [
        claude_bin, "-p", prompt,
        "--model", str(cfg.get("model", "haiku")),
        "--output-format", "json",
        "--no-session-persistence",
        "--disable-slash-commands",
        "--setting-sources", "",
        "--system-prompt", system,
        "--json-schema", json.dumps(schema),
        "--max-budget-usd", str(cfg.get("max_budget_usd", 0.005)),
    ]
    env = {**os.environ}
    env.pop("CLAUDECODE", None)
    env["CLAUDE_CODE_DISABLE_AUTO_MEMORY"] = "1"
    env["CLAUDE_CODE_DISABLE_CLAUDE_MDS"] = "1"
    env["CLAUDE_CODE_DISABLE_CRON"] = "1"

    timeout_s = float(cfg.get("timeout_seconds", 8))
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, env=env, timeout=timeout_s,
        )
    except (subprocess.TimeoutExpired, OSError):
        return None
    if proc.returncode != 0:
        return None

    try:
        envelope = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return None
    structured = envelope.get("structured_output") if isinstance(envelope, dict) else None
    if not isinstance(structured, dict):
        return None
    persona = structured.get("persona")
    confidence = structured.get("confidence")
    if not persona or not isinstance(confidence, (int, float)):
        return None
    min_conf = float(cfg.get("min_confidence", 0.6))
    if confidence < min_conf:
        return None

    # Map persona back to its rule for the phrasing (preferred — matches the
    # tone of keyword suggestions). Fall back to a synthesized phrasing.
    for rule in rules:
        if isinstance(rule, dict) and rule.get("persona") == persona:
            return rule
    return {
        "persona": persona,
        "phrasing": (
            f"Haiku intent classifier suggests `/ce-lite:ce-ask-{persona[3:]}` "
            f"(confidence {confidence:.2f}): {structured.get('reason', '')}"
        ),
    }


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (OSError, json.JSONDecodeError):
        return 0

    user_prompt = payload.get("prompt") if isinstance(payload, dict) else None
    if not isinstance(user_prompt, str) or not user_prompt.strip():
        return 0

    config, rules = _load_config_and_rules()
    if not rules:
        return 0

    matched = _keyword_suggestions(rules, user_prompt.lower())

    # Fallback: if no keyword match, optionally run Haiku classifier.
    if not matched:
        haiku_cfg = config.get("haiku_classifier", {}) if isinstance(config, dict) else {}
        haiku_match = _haiku_classify(user_prompt, rules, haiku_cfg)
        if haiku_match is not None:
            matched = [haiku_match]

    if not matched:
        return 0

    suggestions = "\\n".join(
        f"- {rule.get('phrasing', '').strip()}"
        for rule in matched[:MAX_SUGGESTIONS]
        if rule.get("phrasing")
    )
    if not suggestions:
        return 0

    response = {
        "hookSpecificOutput": {
            "hookEventName": "UserPromptSubmit",
            "additionalContext": (
                "[ce-lite auto-suggest] Based on the prompt content, ce-lite "
                "specialist personas may be relevant:\\n"
                + suggestions
                + "\\nThese dispatch a sub-agent grounded in the persona's "
                "domain expertise — invoke as a slash command for an "
                "independent specialist perspective. (Suggestions only; the "
                "main agent can also handle the work directly if appropriate.)"
            ),
        }
    }
    json.dump(response, sys.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def write_hooks(dist: Path) -> list[Path]:
    """Emit the hook config + rules + script under dist/hooks/."""
    hooks_dir = dist / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    config_path = hooks_dir / "hooks.json"
    rules_path = hooks_dir / "skill-rules.json"
    script_path = hooks_dir / "auto_suggest.py"

    config_path.write_text(render_hook_config(), encoding="utf-8")
    rules_path.write_text(render_hook_rules(), encoding="utf-8")
    script_path.write_text(render_hook_script(), encoding="utf-8")
    # Make script executable (UserPromptSubmit hook spec uses it as a command)
    script_path.chmod(0o755)
    return [config_path, rules_path, script_path]


def main(dist_arg: str, converter_arg: str | None = None) -> int:
    dist = Path(dist_arg).resolve()
    if not dist.is_dir():
        print(f"generate_wrappers.py: dist not found: {dist}", file=sys.stderr)
        return 2

    converter_dir = (
        Path(converter_arg).resolve() if converter_arg else Path(__file__).resolve().parent
    )

    personas = load_manifest(dist)
    overrides = load_overrides(converter_dir)

    used_overrides = 0
    written: list[Path] = []
    for persona in personas:
        description = overrides.get(persona.name, passA_description(persona.description))
        if persona.name in overrides:
            used_overrides += 1
        written.append(write_wrapper(dist, persona, description))

    panel_path = write_panel(dist, personas)
    meta_skill_path = write_meta_skill(dist)
    resolver_path = write_persona_resolver(dist)
    hook_paths = write_hooks(dist)

    # Phase B.7: ce-specialist meta-agent removed — Phase B.6 eval measured
    # 0/2 autonomous-routing recall, confirming the industry-known finding
    # that registered subagents auto-fire ~20% of the time. Replaced by a
    # UserPromptSubmit hook (~84% recall, zero idle cost). If a stale
    # dist/agents/ce-specialist.agent.md is around from an earlier run,
    # remove it now so the install is clean.
    stale_agent = dist / "agents" / "ce-specialist.agent.md"
    if stale_agent.exists():
        stale_agent.unlink()
        agents_dir = dist / "agents"
        try:
            agents_dir.rmdir()  # only succeeds if now empty
        except OSError:
            pass

    print(
        f"generate_wrappers.py: wrote {len(written)} wrappers "
        f"({used_overrides} from overrides, {len(written) - used_overrides} via Pass A) "
        f"+ ce-ask-panel ({panel_path.name}) + ce-ask discovery skill ({meta_skill_path.name}) "
        f"+ bin/ce-lite-persona resolver ({resolver_path.name}) "
        f"+ UserPromptSubmit hook ({len(hook_paths)} files)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("dist", help="path to converted plugin dist/ directory")
    parser.add_argument(
        "--converter-dir",
        default=None,
        help="path to converter/ source dir (default: this script's parent)",
    )
    args = parser.parse_args()
    sys.exit(main(args.dist, args.converter_dir))
