"""Generate per-persona wrapper skills (Tier 3) + bin/ce-lite-persona resolver.

Each entry in `dist/references/agent-prompts/manifest.json` becomes a thin
SKILL.md at `dist/skills/ce-ask-<persona>/SKILL.md`. The wrapper restores
addressability through Claude's skill-routing surface — Claude can
spontaneously suggest `/ce-ask-security-sentinel` when reviewing
security-sensitive code, without re-paying the persistent-agent
registration cost (49 agents × ~1.2k tokens = ~58.8k baseline that the
ce-lite v1 converter strips).

Dispatch lookup is handled by a single small Python shim at
`dist/bin/ce-lite-persona` (this directory is on PATH because Claude Code
exports installed-plugin `bin/`). Wrapper SKILL.md bodies — and the
orchestrator dispatch-protocol preamble injected by `rewrite.py` — just
invoke `ce-lite-persona <name> --body` instead of carrying ~500 tokens of
Glob/find discovery scaffolding each. Net: same idle cost (~22 tok per
wrapper-skill description), lower per-dispatch context cost.

Naming convention: `ce-ask-<persona-bare-name>`. The `ce-` prefix is
stripped from the agent name before re-prefixing with `ce-ask-` so we
get `ce-ask-security-sentinel` rather than `ce-ask-ce-security-sentinel`.
The canonical persona name (`ce-security-sentinel`) stays referenced in
the wrapper body — that's what gets dispatched to the persona prompt
file. Naming this way keeps the canonical names available for a future
Tier 4 (lazy agent registration) re-registration without a name fight.

Description generation is two-pass:

  - Pass A (this script, deterministic): strip the "Conditional X persona,
    selected when..." agent-routing preamble where present; otherwise pass
    the manifest description through unchanged. Cheap baseline.
  - Pass B (run separately, locally, before each release): drive
    `document-skills:skill-creator`'s `improve_description.py` over the
    full set; commit refined descriptions to overrides/persona-descriptions.yaml;
    re-run this generator with overrides applied. Not a CI step (no LLM
    in CI invariant from the parent converter plan).

If `overrides/persona-descriptions.yaml` exists in the converter repo
(sibling to this script), per-persona overrides take precedence over
Pass A output.

The wrapper template embeds:

  1. A "do not edit" marker so round-trip cleanup can identify generated
     files and Tier 4 migration knows what to delete.
  2. A `[ce-persona=<n> via=ce-ask-direct]` trace tag for inline
     debugging (grep transcripts when a routing question comes up; not
     systematic usage data collection).
  3. A tool-restriction self-policing preamble that turns the manifest's
     advisory `tools:` field into loud-advisory inside the dispatched
     prompt (the harness can't enforce because we dispatch via
     general-purpose, but the agent can self-police if explicitly told).
  4. An `Agent.description` template — meaningful labels on the dispatch
     so traces don't read as anonymous "general-purpose" runs.
  5. The canonical persona name in the body (never the wrapper name) so
     Tier 4 migration is a mechanical s/// over wrapper-bodies.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

CONDITIONAL_PREFIX_RE = re.compile(
    r"^Conditional\s+[a-z][a-z\-/]*\s+persona,\s+selected\s+when\s+",
    re.IGNORECASE,
)

WRAPPER_GENERATED_MARKER = (
    "<!-- Generated by ce-lite converter — do not edit. "
    "Regenerate via converter/generate_wrappers.py. -->"
)


# Persona prompts live inside this plugin's install dir. Rather than embed
# Glob/find discovery scaffolding in every wrapper SKILL.md body (~500 tok
# of repeated scaffolding per skill), we ship a `bin/ce-lite-persona`
# resolver. Claude Code exports each installed plugin's `bin/` onto PATH, so
# dispatch sites can invoke `ce-lite-persona <name> --body` directly in one
# Bash call. The resolver itself walks up from its own location (or honours
# $CLAUDE_PLUGIN_ROOT) to find the plugin root; the SKILL.md author doesn't
# need to know the install path.


@dataclass(frozen=True)
class Persona:
    name: str
    description: str
    model: str
    tools: list[str] | None
    prompt_path: str


def load_manifest(dist: Path) -> list[Persona]:
    manifest_path = dist / "references" / "agent-prompts" / "manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"missing manifest: {manifest_path}")
    raw = json.loads(manifest_path.read_text(encoding="utf-8"))
    return [
        Persona(
            name=a["name"],
            description=a["description"],
            model=a.get("model") or "inherit",
            tools=a.get("tools"),
            prompt_path=a["prompt_path"],
        )
        for a in raw["agents"]
    ]


def load_overrides(converter_dir: Path) -> dict[str, str]:
    """Load overrides/persona-descriptions.yaml as a flat name→description map.

    Format (light-touch YAML, no nesting):

        ce-security-sentinel: |
          Use when reviewing for security issues...
        ce-architecture-strategist: "Use when ..."

    Empty file or missing file returns {}. Keep the parser deliberately
    minimal — overrides are populated by skill-creator and committed to
    the repo, not edited at scale by hand.
    """
    overrides_path = converter_dir / "overrides" / "persona-descriptions.yaml"
    if not overrides_path.is_file():
        return {}
    text = overrides_path.read_text(encoding="utf-8")
    result: dict[str, str] = {}
    current_key: str | None = None
    current_val: list[str] = []
    block_indent: int | None = None
    for raw_line in text.splitlines():
        # Skip pure comments / blank lines at top level.
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            if current_key is None:
                continue
        # Top-level key (no leading whitespace, has colon).
        if raw_line and not raw_line[0].isspace() and ":" in raw_line:
            # Flush previous key.
            if current_key is not None:
                result[current_key] = "\n".join(current_val).rstrip()
                current_val = []
                block_indent = None
            key, _, value = raw_line.partition(":")
            current_key = key.strip()
            value = value.strip()
            if value in ("|", ">", "|-", ">-"):
                # Block scalar follows on indented lines.
                continue
            if value:
                # Inline scalar; strip optional quotes.
                if (value.startswith('"') and value.endswith('"')) or (
                    value.startswith("'") and value.endswith("'")
                ):
                    value = value[1:-1]
                result[current_key] = value
                current_key = None
                current_val = []
                block_indent = None
            continue
        # Indented continuation of a block scalar.
        if current_key is not None and raw_line and raw_line[0].isspace():
            # Establish block indent on first content line.
            indent = len(raw_line) - len(raw_line.lstrip())
            if block_indent is None:
                block_indent = indent
            # Strip the common indent.
            current_val.append(raw_line[block_indent:])
    if current_key is not None:
        result[current_key] = "\n".join(current_val).rstrip()
    return result


def wrapper_name(persona_name: str) -> str:
    """ce-security-sentinel → ce-ask-security-sentinel."""
    if persona_name.startswith("ce-"):
        return f"ce-ask-{persona_name[3:]}"
    return f"ce-ask-{persona_name}"


def passA_description(manifest_desc: str) -> str:
    """Strip the agent-routing 'Conditional X, selected when...' preamble.

    Most upstream descriptions are already action-oriented; only the
    'Conditional' family of personas reads as agent-routing language and
    benefits from rewriting. Pass through unchanged otherwise — Pass B
    (skill-creator-driven) will tune the rest.
    """
    if CONDITIONAL_PREFIX_RE.match(manifest_desc):
        rest = CONDITIONAL_PREFIX_RE.sub("", manifest_desc, count=1)
        return f"Use when {rest}"
    return manifest_desc


def render_wrapper(persona: Persona, description: str) -> str:
    return f"""\
---
name: {wrapper_name(persona.name)}
description: {json.dumps(description)}
---

{WRAPPER_GENERATED_MARKER}

Dispatch the **{persona.name}** specialist as a sub-agent.

1. Run `ce-lite-persona {persona.name} --prefix` via Bash. Output is the
   full prompt prefix — persona body, `[ce-persona={persona.name} via=ce-ask-direct]`
   trace tag, and the tool-restriction self-policing preamble derived from the
   manifest — ready to concatenate with the task. Non-zero exit means the
   resolver hit an error (unknown persona, missing prompt file, partial
   install); surface stderr and stop without falling back.

2. Spawn `Agent` with `subagent_type: "general-purpose"` and
   `description: "{persona.name}: <one-line task summary>"` so traces stay
   readable. `prompt` is the resolver's stdout from step 1, a blank line,
   then `$ARGUMENTS`. The task is never passed through Bash on the resolver
   call — concatenate it into the Agent.prompt parameter directly.

For parallel multi-persona dispatch, see `/ce-ask-panel`.
"""


def write_wrapper(dist: Path, persona: Persona, description: str) -> Path:
    skill_dir = dist / "skills" / wrapper_name(persona.name)
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(render_wrapper(persona, description), encoding="utf-8")
    return skill_path


PANEL_DESCRIPTION = (
    "Use to consult several persona specialists in parallel and merge their "
    "findings into one response. Provide a comma-separated list of persona "
    "names plus the task context. Bridges single-persona reach (one ce-ask-* "
    "skill) and full orchestrator pipelines (ce-code-review etc.) when you "
    "want N specific perspectives but not the full review pipeline."
)


def render_panel(personas: list[Persona]) -> str:
    """Render the ce-ask-panel meta-skill body.

    Static template — same regardless of which personas exist; the runtime
    validates against the live manifest via the ce-lite-persona resolver.
    Listing personas at generation time would force regeneration on every
    upstream tag bump just to update a list Claude can read from
    manifest.json directly.
    """
    return f"""\
---
name: ce-ask-panel
description: {json.dumps(PANEL_DESCRIPTION)}
argument-hint: "<persona1>,<persona2>,... <task context>"
---

{WRAPPER_GENERATED_MARKER}

Dispatch a panel of multiple persona specialists in parallel and merge their
findings into one response. Bridges single-persona ad-hoc reach
(`/ce-ask-<one-persona>`) and the full orchestrator pipelines
(`/ce-code-review`, `/ce-doc-review`, `/ce-resolve-pr-feedback`) — use this
when you want N specific perspectives without the rest of the pipeline.

## Usage

`/ce-ask-panel <persona1>,<persona2>,... <task context>`

Persona names are the **canonical** names from the plugin's persona manifest
(e.g. `ce-security-sentinel`, `ce-architecture-strategist`), NOT the
`ce-ask-*` wrapper names.

## Steps

1. Parse the first whitespace-delimited token as a comma-separated persona
   list (trim each name). Treat the rest as the user's task context.

2. Validate each persona by running `ce-lite-persona <name> --path` via
   Bash. Non-zero exit means an unknown persona — the resolver's stderr
   lists all known personas. Surface that to the user and stop without
   dispatching anything; partial dispatches confuse merged output.

3. For each validated persona, dispatch in parallel via `Agent` with
   `subagent_type: "general-purpose"` and
   `description: "<persona>: <task summary>"` (meaningful trace label).
   The prompt is the output of
   `ce-lite-persona <persona> --prefix --via ce-ask-panel`, a blank line,
   then the user-supplied task context. The task is concatenated into the
   Agent.prompt parameter directly — not passed to the resolver.

4. Wait for all dispatches to complete. Merge into one response, grouping
   by persona with section headers (`## <persona> findings`). Preserve each
   persona's structured output — don't collapse into prose.

## Notes

- Trace tag `via=ce-ask-panel` distinguishes panel dispatch from direct
  invocation (`via=ce-ask-direct`) when grepping transcripts.
- For one persona, prefer `/ce-ask-<persona-bare-name>` — cheaper than
  going through the panel parser.
- For full-pipeline reviews, prefer the orchestrator skills
  (`/ce-code-review`, `/ce-doc-review`) which include conditional persona
  selection.
"""


def write_panel(dist: Path, personas: list[Persona]) -> Path:
    skill_dir = dist / "skills" / "ce-ask-panel"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(render_panel(personas), encoding="utf-8")
    return skill_path


META_SKILL_DESCRIPTION = (
    "Discover and dispatch ce-lite specialist personas via a single slash command. "
    "Run with no args to browse the persona catalog (security, architecture, "
    "correctness, simplicity, pattern, performance, data-integrity, doc review, "
    "and more). Run with `<persona-name>` to see one persona's role. Run with "
    "`<persona-name> <task>` to dispatch that specialist on the task. For "
    "tab-complete-friendly invocation use `/ce-ask-<persona>` directly; for "
    "parallel multi-persona dispatch use `/ce-ask-panel`."
)


DEFAULT_HOOK_RULES = {
    "config": {
        "haiku_classifier": {
            "enabled": False,
            "model": "haiku",
            "max_budget_usd": 0.005,
            "timeout_seconds": 8,
            "min_confidence": 0.6,
            "_doc": (
                "Optional Haiku-based intent classifier. When enabled, the "
                "hook falls back to a Haiku call if keyword matching produces "
                "no hit. Haiku reads the user prompt + persona catalog and "
                "returns a structured suggestion. Adds ~1–2s latency per "
                "non-keyword-matching prompt and ~$0.001 quota each. Set "
                "enabled=true to opt in. The keyword path always runs first "
                "(cheap and deterministic); Haiku is the no-keyword "
                "fallback only."
            ),
        }
    },
    "rules": [
        {
            "keywords": [
                "security",
                "vuln",
                "vulnerab",
                "OWASP",
                "injection",
                "XSS",
                "CSRF",
                "SSRF",
                "auth ",
                "auth-",
                "JWT",
                "OAuth",
                "mass assignment",
                "sanitiz",
                "hardcoded secret",
                "credential leak",
                "open redirect",
                "deserialization",
                "is this safe",
                "paranoid review",
                "is it safe to ship",
                "before we ship",
            ],
            "persona": "ce-security-sentinel",
            "phrasing": (
                "The prompt looks security-flavored. Consider running "
                "`/ce-lite:ce-ask-security-sentinel` (or invoking the wrapper "
                "via Skill) for a focused security review by a specialist "
                "persona. The wrapper dispatches a sub-agent grounded in "
                "OWASP / injection / authn-authz / secrets-handling expertise."
            ),
        },
        {
            "keywords": [
                "factor out",
                "extract method",
                "extract class",
                "duplicat",
                "copy-pasted",
                "DRY",
                "coupling",
                "abstraction",
                "boundaries",
                "structural refactor",
                "service boundaries",
                "module bound",
                "pattern compliance",
                "design integrity",
            ],
            "persona": "ce-architecture-strategist",
            "phrasing": (
                "Architecture/design concerns visible. Consider "
                "`/ce-lite:ce-ask-architecture-strategist` for a structural "
                "review (pattern compliance, layer violations, naming "
                "consistency)."
            ),
        },
        {
            "keywords": [
                "YAGNI",
                "over-engineered",
                "premature abstraction",
                "redundant abstraction",
                "simplify",
                "simpler way",
                "is this too clever",
                "unnecessary indirection",
                "feels overcomplicated",
                "could this be simpler",
            ],
            "persona": "ce-code-simplicity-reviewer",
            "phrasing": (
                "Simplicity concerns visible. Consider "
                "`/ce-lite:ce-ask-code-simplicity-reviewer` for a YAGNI/"
                "redundancy review."
            ),
        },
        {
            "keywords": [
                "edge case",
                "off-by-one",
                "race condition",
                "deadlock",
                "concurrency bug",
                "correctness",
                "logic bug",
                "is this correct",
                "boundary condition",
            ],
            "persona": "ce-correctness-reviewer",
            "phrasing": (
                "Correctness concerns visible. Consider "
                "`/ce-lite:ce-ask-correctness-reviewer` for an edge-case / "
                "boundary-condition review."
            ),
        },
        {
            "keywords": [
                "naming consistency",
                "convention drift",
                "style consistency",
                "naming pattern",
                "matches existing",
                "consistent with",
                "follow the pattern",
            ],
            "persona": "ce-pattern-recognition-specialist",
            "phrasing": (
                "Pattern/consistency review may help. Consider "
                "`/ce-lite:ce-ask-pattern-recognition-specialist` to surface "
                "duplication and convention drift."
            ),
        },
        {
            "keywords": [
                "performance",
                "latency",
                "bottleneck",
                "slow query",
                "N+1",
                "p99",
                "throughput",
                "memory pressure",
            ],
            "persona": "ce-performance-oracle",
            "phrasing": (
                "Performance angle visible. Consider "
                "`/ce-lite:ce-ask-performance-oracle` for a structured "
                "performance review."
            ),
        },
    ],
}


def render_meta_skill() -> str:
    """Render the /ce-ask single-slash-command catalog/dispatch surface.

    Catalog is read from manifest.json at runtime — body stays stable across
    upstream tag bumps even when persona list changes. Per-persona wrappers
    (/ce-ask-<persona>) provide tab-complete-friendly explicit invocation; this
    meta-skill provides the discoverable single-command surface for users who
    don't have a specific persona name in mind yet.
    """
    return f"""\
---
name: ce-ask
description: {json.dumps(META_SKILL_DESCRIPTION)}
argument-hint: "[persona-name [task context]]"
---

{WRAPPER_GENERATED_MARKER}

Single discoverable entry point to ce-lite specialist personas. Three modes
based on argument shape.

## Usage

- `/ce-ask` — print the persona catalog (name + specialty for each).
- `/ce-ask <persona>` — show one persona's full role definition.
- `/ce-ask <persona> <task>` — dispatch that persona on the task.

Persona names are the canonical names from the manifest (e.g.
`ce-security-sentinel`). Argument parsing: first whitespace-delimited token
is the persona name; everything after is the task context.

## Steps

1. **No args** — run `ce-lite-persona --list` via Bash and present the
   output (one persona per line, `<name><TAB><description>`). The resolver
   reads the manifest at runtime; no regeneration is needed when upstream
   adds or removes personas. Stop.

2. **Persona name only** — run `ce-lite-persona <name> --body` and present
   the role definition. Non-zero exit means an unknown persona; surface the
   resolver's stderr (it lists known names) and stop.

3. **Persona name + task** — dispatch via `Agent` with
   `subagent_type: "general-purpose"` and
   `description: "<persona>: <task summary>"` (meaningful trace label).
   The prompt is the output of
   `ce-lite-persona <persona> --prefix --via ce-ask-meta`, a blank line,
   then the user task. The task is concatenated into the Agent.prompt
   parameter directly — not passed to the resolver.

## Notes

- Tab-complete-friendly explicit invocation: `/ce-ask-<persona-name>` (one
  per persona).
- Parallel multi-persona dispatch: `/ce-ask-panel <a>,<b>,<c> <task>`.
- The catalog is read from `manifest.json` at runtime via the resolver, so
  this skill body doesn't need regeneration when the persona list changes.
"""


def write_meta_skill(dist: Path) -> Path:
    skill_dir = dist / "skills" / "ce-ask"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(render_meta_skill(), encoding="utf-8")
    return skill_path


# ---- bin/ce-lite-persona resolver shim ----
#
# Skills can't enumerate the plugin install path declaratively. Claude Code
# exports each installed plugin's `bin/` onto PATH, so we ship a tiny stdlib-
# only Python script there: SKILL.md bodies just call
# `ce-lite-persona <name> --body` in one Bash invocation instead of carrying
# Glob/find scaffolding. The resolver walks up from its own location (or
# honours $CLAUDE_PLUGIN_ROOT, which is set in hook subprocesses) to find
# the plugin root, validates against manifest.json, and prints the prompt
# path or body. Errors land on stderr with non-zero exit and a one-line
# `ce-lite-persona: <reason>` prefix.


_RESOLVER_SOURCE_PATH = Path(__file__).parent / "resources" / "ce-lite-persona"


def render_persona_resolver() -> str:
    """Read the resolver source. Preserved for tests that assert against content.

    The build path uses write_persona_resolver() which copies the file directly.
    """
    if not _RESOLVER_SOURCE_PATH.is_file():
        raise FileNotFoundError(f"missing resolver source at {_RESOLVER_SOURCE_PATH}")
    return _RESOLVER_SOURCE_PATH.read_text(encoding="utf-8")


def write_persona_resolver(dist: Path) -> Path:
    """Copy converter/resources/ce-lite-persona → dist/bin/ce-lite-persona.

    Resolver source lives at converter/resources/ce-lite-persona as a real
    Python file (lintable, testable, syntax-highlighted in editors). The
    generator stamps it into dist/bin/ at build time. Keep that source
    stdlib-only and free of converter imports — it ships to end-user
    installs and runs there independently.
    """
    bin_dir = dist / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    resolver_path = bin_dir / "ce-lite-persona"
    if not _RESOLVER_SOURCE_PATH.is_file():
        raise FileNotFoundError(
            f"missing resolver source at {_RESOLVER_SOURCE_PATH} — "
            "converter/resources/ce-lite-persona must exist for the build to "
            "stamp it into dist/bin/."
        )
    shutil.copy2(_RESOLVER_SOURCE_PATH, resolver_path)
    resolver_path.chmod(0o755)
    return resolver_path


# ---- UserPromptSubmit hook (Phase B.7) ----
#
# Phase B.5's meta-agent (ce-specialist) didn't fire autonomously — the
# integration eval (Phase B.6) measured 0/2 on autonomous review prompts even
# with the agent registered and visible to claude -p. Industry-wide
# research (scottspence.com, paddo.dev, jefflester/claude-skills-supercharged,
# spences10/claude-skills-cli) converges on the same finding: skills/agents
# auto-activate ~20% of the time even with good descriptions, because Claude
# defaults to handling tasks itself rather than delegating to specialists.
#
# The proven workaround is a UserPromptSubmit hook that detects review-flavored
# keywords and injects a suggestion ("consider /ce-ask-<persona>") into the
# prompt before Claude sees it. Measured activation rates jump to 70–84% with
# this approach. Cost is per-matching-prompt (a few hundred tokens of
# injected suggestion), zero at idle — much cheaper than a registered agent
# (~2k always-on) for occasional users.
#
# References:
#   https://scottspence.com/posts/claude-code-skills-dont-auto-activate
#   https://paddo.dev/blog/claude-skills-hooks-solution/
#   https://github.com/anthropics/claude-code/issues/9716


def render_hook_config() -> str:
    """Emit dist/hooks/hooks.json — Claude Code's hook declaration spec."""
    return (
        json.dumps(
            {
                "description": (
                    "ce-lite UserPromptSubmit hook: detect review-flavored prompts and "
                    "suggest invoking the matching specialist persona wrapper. Pure "
                    "keyword matching; no LLM call per prompt; no idle-context cost."
                ),
                "hooks": {
                    "UserPromptSubmit": [
                        {
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/auto_suggest.py",
                                    "timeout": 5,
                                }
                            ]
                        }
                    ]
                },
            },
            indent=2,
        )
        + "\n"
    )


def render_hook_rules() -> str:
    """Emit dist/hooks/skill-rules.json — keyword → persona suggestion table.

    This file is the curated extension point. Each release of the converter
    can ship updated default rules; downstream users can override by replacing
    skill-rules.json with their own (any plugin-cache rebuild from upstream
    overwrites it, so persistent customisation should live in a separate
    user-level hook). Keywords are case-insensitive substring matches.
    """
    return json.dumps(DEFAULT_HOOK_RULES, indent=2) + "\n"


_HOOK_SCRIPT_SOURCE_PATH = Path(__file__).parent / "resources" / "auto_suggest.py"


def render_hook_script() -> str:
    """Read the hook script source. Preserved for tests that assert against content.

    The build path uses write_hooks() which copies the file directly.
    """
    if not _HOOK_SCRIPT_SOURCE_PATH.is_file():
        raise FileNotFoundError(
            f"missing hook script source at {_HOOK_SCRIPT_SOURCE_PATH}"
        )
    return _HOOK_SCRIPT_SOURCE_PATH.read_text(encoding="utf-8")


def write_hooks(dist: Path) -> list[Path]:
    """Emit the hook config + rules + script under dist/hooks/."""
    hooks_dir = dist / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    config_path = hooks_dir / "hooks.json"
    rules_path = hooks_dir / "skill-rules.json"
    script_path = hooks_dir / "auto_suggest.py"

    config_path.write_text(render_hook_config(), encoding="utf-8")
    rules_path.write_text(render_hook_rules(), encoding="utf-8")
    if not _HOOK_SCRIPT_SOURCE_PATH.is_file():
        raise FileNotFoundError(
            f"missing hook script source at {_HOOK_SCRIPT_SOURCE_PATH} — "
            "converter/resources/auto_suggest.py must exist for the build."
        )
    shutil.copy2(_HOOK_SCRIPT_SOURCE_PATH, script_path)
    # Make script executable (UserPromptSubmit hook spec uses it as a command)
    script_path.chmod(0o755)
    return [config_path, rules_path, script_path]


def main(dist_arg: str, converter_arg: str | None = None) -> int:
    dist = Path(dist_arg).resolve()
    if not dist.is_dir():
        print(f"generate_wrappers.py: dist not found: {dist}", file=sys.stderr)
        return 2

    converter_dir = (
        Path(converter_arg).resolve()
        if converter_arg
        else Path(__file__).resolve().parent
    )

    personas = load_manifest(dist)
    overrides = load_overrides(converter_dir)

    used_overrides = 0
    written: list[Path] = []
    for persona in personas:
        description = overrides.get(
            persona.name, passA_description(persona.description)
        )
        if persona.name in overrides:
            used_overrides += 1
        written.append(write_wrapper(dist, persona, description))

    panel_path = write_panel(dist, personas)
    meta_skill_path = write_meta_skill(dist)
    resolver_path = write_persona_resolver(dist)
    hook_paths = write_hooks(dist)

    # Phase B.7: ce-specialist meta-agent removed — Phase B.6 eval measured
    # 0/2 autonomous-routing recall, confirming the industry-known finding
    # that registered subagents auto-fire ~20% of the time. Replaced by a
    # UserPromptSubmit hook (~84% recall, zero idle cost). If a stale
    # dist/agents/ce-specialist.agent.md is around from an earlier run,
    # remove it now so the install is clean.
    stale_agent = dist / "agents" / "ce-specialist.agent.md"
    if stale_agent.exists():
        stale_agent.unlink()
        agents_dir = dist / "agents"
        try:
            agents_dir.rmdir()  # only succeeds if now empty
        except OSError:
            pass

    print(
        f"generate_wrappers.py: wrote {len(written)} wrappers "
        f"({used_overrides} from overrides, {len(written) - used_overrides} via Pass A) "
        f"+ ce-ask-panel ({panel_path.name}) + ce-ask discovery skill ({meta_skill_path.name}) "
        f"+ bin/ce-lite-persona resolver ({resolver_path.name}) "
        f"+ UserPromptSubmit hook ({len(hook_paths)} files)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("dist", help="path to converted plugin dist/ directory")
    parser.add_argument(
        "--converter-dir",
        default=None,
        help="path to converter/ source dir (default: this script's parent)",
    )
    args = parser.parse_args()
    sys.exit(main(args.dist, args.converter_dir))
