"""Generate slash-command wrappers for every skill in dist/skills/.

Why this stage exists: Claude Code auto-registers plugin-namespaced skill
entries in the slash-command autocomplete (e.g. `/ce-lite:ce-plan`), but
dispatch from those auto-registered entries is unreliable — autocomplete
shows the entry, submit doesn't always fire the underlying Skill. Plugins
that ship explicit `commands/<name>.md` files dispatch reliably because
slash commands from `commands/` are a first-class harness concept,
distinct from the skill-routing surface.

For each `dist/skills/<name>/SKILL.md`, this stage emits a thin
`dist/commands/<name>.md` whose body explicitly instructs the model to
invoke the matching skill with `$ARGUMENTS`. The skill body itself is
NOT duplicated — that would drift on every upstream bump and double the
disk footprint. The wrapper is ~10 lines.

Run order: after `generate_wrappers.py` (so the 49 persona wrappers + 2
meta-skills exist in dist/skills/) and before `validate.py` (which will
cross-check that every command maps to a skill and vice versa).
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

# Make extract importable when invoked as a script
sys.path.insert(0, str(Path(__file__).resolve().parent))

from extract import parse_frontmatter  # noqa: E402

COMMAND_GENERATED_MARKER = (
    "<!-- Generated by ce-lite converter — do not edit. "
    "Regenerate via converter/generate_commands.py. -->"
)

# Hard cap on description length for slash-command autocomplete display.
# Skill descriptions are often multi-sentence trigger blurbs; the autocomplete
# row truncates anyway, but a shorter explicit cap keeps the rendered list
# scannable and avoids passing huge strings through the harness.
MAX_DESCRIPTION_LEN = 140


def shorten_description(description: str) -> str:
    """Reduce a skill description to a single autocomplete-friendly line.

    Strategy: take the first sentence (up to first '. ' boundary), then hard-
    truncate to MAX_DESCRIPTION_LEN with an ellipsis if still too long. Skill
    descriptions are often paragraphs of trigger phrasing — the command file
    only needs the action-oriented headline.
    """
    text = " ".join(description.split())  # collapse internal whitespace
    if not text:
        return ""
    # First-sentence split. Look for ". " (period + space), not bare "." which
    # would split on abbreviations like "etc." or version numbers.
    period_idx = text.find(". ")
    if 0 < period_idx < MAX_DESCRIPTION_LEN:
        text = text[: period_idx + 1]
    if len(text) > MAX_DESCRIPTION_LEN:
        text = text[: MAX_DESCRIPTION_LEN - 3].rstrip() + "..."
    return text


def render_command(skill_name: str, description: str, argument_hint: str | None) -> str:
    """Render the command-file body for one skill."""
    fm_lines = [
        f"description: {json.dumps(description)}",
    ]
    if argument_hint:
        fm_lines.append(f"argument-hint: {json.dumps(argument_hint)}")
    frontmatter = "\n".join(fm_lines)

    return f"""\
---
{frontmatter}
---

{COMMAND_GENERATED_MARKER}

Use the `{skill_name}` skill (from the ce-lite plugin) to handle this request.

Arguments: $ARGUMENTS
"""


def collect_skills(dist: Path) -> list[tuple[str, str, str | None]]:
    """Return [(skill_name, description, argument_hint?), ...] for every SKILL.md.

    Fails loud if any SKILL.md has malformed frontmatter or no `name:` — the
    same skills will be expected to exist by validate.py, so silent skips
    would just push the failure to a less obvious place.
    """
    skills_dir = dist / "skills"
    if not skills_dir.is_dir():
        raise FileNotFoundError(f"missing {skills_dir}")

    out: list[tuple[str, str, str | None]] = []
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        text = skill_md.read_text(encoding="utf-8")
        try:
            fm, _ = parse_frontmatter(text)
        except ValueError as exc:
            raise ValueError(f"{skill_md}: {exc}") from exc
        name = fm.get("name")
        if not name:
            raise ValueError(f"{skill_md}: SKILL.md has no 'name' in frontmatter")
        # Sanity: skill dir name should match the SKILL.md name field
        if skill_md.parent.name != name:
            raise ValueError(
                f"{skill_md}: skill dir {skill_md.parent.name!r} does not match "
                f"frontmatter name {name!r}"
            )
        description = fm.get("description") or ""
        argument_hint = fm.get("argument-hint") or None
        out.append((name, description, argument_hint))
    return out


def write_commands(dist: Path, skills: list[tuple[str, str, str | None]]) -> list[Path]:
    commands_dir = dist / "commands"
    # Always start from a clean dir so renames in dist/skills/ propagate cleanly.
    if commands_dir.exists():
        shutil.rmtree(commands_dir)
    commands_dir.mkdir(parents=True)

    written: list[Path] = []
    for name, description, argument_hint in skills:
        short = shorten_description(description)
        body = render_command(name, short, argument_hint)
        out_path = commands_dir / f"{name}.md"
        out_path.write_text(body, encoding="utf-8")
        written.append(out_path)
    return written


def main(dist_arg: str) -> int:
    dist = Path(dist_arg).resolve()
    if not dist.is_dir():
        print(f"generate_commands.py: dist not found: {dist}", file=sys.stderr)
        return 2

    skills = collect_skills(dist)
    written = write_commands(dist, skills)

    print(
        f"generate_commands.py: wrote {len(written)} command wrappers "
        f"to {dist / 'commands'}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("dist", help="path to converted plugin dist/ directory")
    args = parser.parse_args()
    sys.exit(main(args.dist))
