"""Generate per-persona wrapper skills (Tier 3).

Each entry in `dist/references/agent-prompts/manifest.json` becomes a thin
SKILL.md at `dist/skills/ce-ask-<persona>/SKILL.md`. The wrapper restores
addressability through Claude's skill-routing surface — Claude can
spontaneously suggest `/ce-ask-security-sentinel` when reviewing
security-sensitive code, without re-paying the persistent-agent
registration cost (49 agents × ~1.2k tokens = ~58.8k baseline that the
ce-lite v1 converter strips).

Naming convention: `ce-ask-<persona-bare-name>`. The `ce-` prefix is
stripped from the agent name before re-prefixing with `ce-ask-` so we
get `ce-ask-security-sentinel` rather than `ce-ask-ce-security-sentinel`.
The canonical persona name (`ce-security-sentinel`) stays referenced in
the wrapper body — that's what gets dispatched to the persona prompt
file. Naming this way keeps the canonical names available for a future
Tier 4 (lazy agent registration) re-registration without a name fight.

Description generation is two-pass:

  - Pass A (this script, deterministic): strip the "Conditional X persona,
    selected when..." agent-routing preamble where present; otherwise pass
    the manifest description through unchanged. Cheap baseline.
  - Pass B (run separately, locally, before each release): drive
    `document-skills:skill-creator`'s `improve_description.py` over the
    full set; commit refined descriptions to overrides/persona-descriptions.yaml;
    re-run this generator with overrides applied. Not a CI step (no LLM
    in CI invariant from the parent converter plan).

If `overrides/persona-descriptions.yaml` exists in the converter repo
(sibling to this script), per-persona overrides take precedence over
Pass A output.

The wrapper template embeds:

  1. A "do not edit" marker so round-trip cleanup can identify generated
     files and Tier 4 migration knows what to delete.
  2. A `[ce-persona=<n> via=ce-ask-direct]` trace tag for inline
     debugging (grep transcripts when a routing question comes up; not
     systematic usage data collection).
  3. A tool-restriction self-policing preamble that turns the manifest's
     advisory `tools:` field into loud-advisory inside the dispatched
     prompt (the harness can't enforce because we dispatch via
     general-purpose, but the agent can self-police if explicitly told).
  4. A missing-prompt-file fallback that reports the rename rather than
     silently failing.
  5. The canonical persona name in the body (never the wrapper name) so
     Tier 4 migration is a mechanical s/// over wrapper-bodies.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

CONDITIONAL_PREFIX_RE = re.compile(
    r"^Conditional\s+[a-z][a-z\-/]*\s+persona,\s+selected\s+when\s+",
    re.IGNORECASE,
)

WRAPPER_GENERATED_MARKER = (
    "<!-- Generated by ce-lite converter — do not edit. "
    "Regenerate via converter/generate_wrappers.py. -->"
)


# Persona prompts live inside this plugin's install dir, but the install path
# varies per machine and a bare relative path resolves relative to the user's
# project (which is wrong). Every dispatch site needs the same discovery
# protocol — keep it as one canonical block so the four templates stay in sync.
PROMPT_DISCOVERY_INSTRUCTIONS = """\
> **Locating the plugin's persona prompts.** A bare `references/agent-prompts/`
> path resolves relative to the user's project, which is usually not where
> this plugin is installed. Use Glob (rooted at `~`) to find the actual path:
>
> ```
> **/.claude/plugins/cache/ce-lite/*/references/agent-prompts/<name>.md
> ```
>
> If that pattern returns nothing, fall back to `Bash`:
>
> ```
> find ~/.claude/plugins/cache -name '<name>.md' -path '*/agent-prompts/*' 2>/dev/null | head -1
> ```
>
> Cache the discovered plugin root (the directory containing
> `.claude-plugin/plugin.json`) — every persona prompt lives under the same
> root, so subsequent lookups in this turn don't need to re-glob."""


@dataclass(frozen=True)
class Persona:
    name: str
    description: str
    model: str
    tools: list[str] | None
    prompt_path: str


def load_manifest(dist: Path) -> list[Persona]:
    manifest_path = dist / "references" / "agent-prompts" / "manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"missing manifest: {manifest_path}")
    raw = json.loads(manifest_path.read_text(encoding="utf-8"))
    return [
        Persona(
            name=a["name"],
            description=a["description"],
            model=a.get("model") or "inherit",
            tools=a.get("tools"),
            prompt_path=a["prompt_path"],
        )
        for a in raw["agents"]
    ]


def load_overrides(converter_dir: Path) -> dict[str, str]:
    """Load overrides/persona-descriptions.yaml as a flat name→description map.

    Format (light-touch YAML, no nesting):

        ce-security-sentinel: |
          Use when reviewing for security issues...
        ce-architecture-strategist: "Use when ..."

    Empty file or missing file returns {}. Keep the parser deliberately
    minimal — overrides are populated by skill-creator and committed to
    the repo, not edited at scale by hand.
    """
    overrides_path = converter_dir / "overrides" / "persona-descriptions.yaml"
    if not overrides_path.is_file():
        return {}
    text = overrides_path.read_text(encoding="utf-8")
    result: dict[str, str] = {}
    current_key: str | None = None
    current_val: list[str] = []
    block_indent: int | None = None
    for raw_line in text.splitlines():
        # Skip pure comments / blank lines at top level.
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            if current_key is None:
                continue
        # Top-level key (no leading whitespace, has colon).
        if raw_line and not raw_line[0].isspace() and ":" in raw_line:
            # Flush previous key.
            if current_key is not None:
                result[current_key] = "\n".join(current_val).rstrip()
                current_val = []
                block_indent = None
            key, _, value = raw_line.partition(":")
            current_key = key.strip()
            value = value.strip()
            if value in ("|", ">", "|-", ">-"):
                # Block scalar follows on indented lines.
                continue
            if value:
                # Inline scalar; strip optional quotes.
                if (value.startswith('"') and value.endswith('"')) or (
                    value.startswith("'") and value.endswith("'")
                ):
                    value = value[1:-1]
                result[current_key] = value
                current_key = None
                current_val = []
                block_indent = None
            continue
        # Indented continuation of a block scalar.
        if current_key is not None and raw_line and raw_line[0].isspace():
            # Establish block indent on first content line.
            indent = len(raw_line) - len(raw_line.lstrip())
            if block_indent is None:
                block_indent = indent
            # Strip the common indent.
            current_val.append(raw_line[block_indent:])
    if current_key is not None:
        result[current_key] = "\n".join(current_val).rstrip()
    return result


def wrapper_name(persona_name: str) -> str:
    """ce-security-sentinel → ce-ask-security-sentinel."""
    if persona_name.startswith("ce-"):
        return f"ce-ask-{persona_name[3:]}"
    return f"ce-ask-{persona_name}"


def passA_description(manifest_desc: str) -> str:
    """Strip the agent-routing 'Conditional X, selected when...' preamble.

    Most upstream descriptions are already action-oriented; only the
    'Conditional' family of personas reads as agent-routing language and
    benefits from rewriting. Pass through unchanged otherwise — Pass B
    (skill-creator-driven) will tune the rest.
    """
    if CONDITIONAL_PREFIX_RE.match(manifest_desc):
        rest = CONDITIONAL_PREFIX_RE.sub("", manifest_desc, count=1)
        return f"Use when {rest}"
    return manifest_desc


def render_wrapper(persona: Persona, description: str) -> str:
    tools_str = ", ".join(persona.tools) if persona.tools else "any"
    return f"""\
---
name: {wrapper_name(persona.name)}
description: {json.dumps(description)}
---

{WRAPPER_GENERATED_MARKER}

Dispatch the **{persona.name}** specialist by spawning a sub-agent with the
persona's prompt body as preamble. The persona is one of the lightweight-
delegation specialists in this plugin; its prompt body lives at
`{persona.prompt_path}` **inside the plugin's install directory** (NOT the
user's project — see discovery instructions below).

{PROMPT_DISCOVERY_INSTRUCTIONS}

## Steps

1. Locate the prompt file via the discovery instructions above. Then read
   the resolved path (`<plugin-root>/{persona.prompt_path}`) for the
   persona's full role definition.
2. Spawn a new agent with `subagent_type: "general-purpose"` (the harness's
   default fan-out type — persistent registrations were stripped to keep this
   plugin's idle context cost low). Prepend the following preamble to the
   prompt before the user-supplied task context:

   ```
   [ce-persona={persona.name} via=ce-ask-direct]

   You are operating as the {persona.name} specialist. Your role is defined
   in the prompt body above. Manifest declares this role uses
   tools=[{tools_str}] and model={persona.model}. Honour those constraints:
   if a task pulls you toward tools outside that set, stop and explain why
   your role requires it — don't silently broaden scope.
   ```

3. Pass the user-supplied task context after the preamble.

## Missing-prompt fallback

If the discovery step returns no plugin root, OR the resolved
`<plugin-root>/{persona.prompt_path}` does not exist (upstream rename,
partial install), report:

> Persona `{persona.name}` not found in this plugin's manifest. The plugin
> may not be installed, may have been partially installed, or the persona
> may have been renamed upstream. Re-install the plugin or regenerate the
> converter dist.

Do **not** silently fall back to a different persona — the user explicitly
named this specialist.

## Notes

- Trace tag `[ce-persona={persona.name} via=ce-ask-direct]` is inline debug
  metadata. `grep` transcripts when investigating routing or behaviour
  questions; no systematic collection.
- For a multi-persona panel, see `/ce-ask-panel`.
"""


def write_wrapper(dist: Path, persona: Persona, description: str) -> Path:
    skill_dir = dist / "skills" / wrapper_name(persona.name)
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(render_wrapper(persona, description), encoding="utf-8")
    return skill_path


PANEL_DESCRIPTION = (
    "Use to consult several persona specialists in parallel and merge their "
    "findings into one response. Provide a comma-separated list of persona "
    "names plus the task context. Bridges single-persona reach (one ce-ask-* "
    "skill) and full orchestrator pipelines (ce-code-review etc.) when you "
    "want N specific perspectives but not the full review pipeline."
)


def render_panel(personas: list[Persona]) -> str:
    """Render the ce-ask-panel meta-skill body.

    Static template — same regardless of which personas exist; the runtime
    validates against the live manifest. Listing personas at generation time
    would force regeneration on every upstream tag bump just to update a list
    Claude can read from manifest.json directly.
    """
    return f"""\
---
name: ce-ask-panel
description: {json.dumps(PANEL_DESCRIPTION)}
argument-hint: "<persona1>,<persona2>,... <task context>"
---

{WRAPPER_GENERATED_MARKER}

Dispatch a panel of multiple persona specialists in parallel and merge their
findings into one response. Bridges single-persona ad-hoc reach
(`/ce-ask-<one-persona>`) and the full orchestrator pipelines
(`/ce-code-review`, `/ce-doc-review`, `/ce-resolve-pr-feedback`) — use this
when you want N specific perspectives without the rest of the pipeline.

## Usage

`/ce-ask-panel <persona1>,<persona2>,... <task context>`

Persona names are the **canonical** names from the plugin's persona manifest
(e.g. `ce-security-sentinel`, `ce-architecture-strategist`), NOT the
`ce-ask-*` wrapper names.

{PROMPT_DISCOVERY_INSTRUCTIONS}

## Steps

1. Parse the first whitespace-delimited token as a comma-separated persona
   list. Trim each name. Treat the rest of the input as the user's task
   context.
2. Locate the plugin root via the discovery instructions above and read
   `<plugin-root>/references/agent-prompts/manifest.json`. Validate each
   named persona is in `agents[].name`. If any are unknown:

   > Unknown persona(s): `<list>`. Known personas: `<list-from-manifest>`.
   > Use the canonical names (e.g. `ce-security-sentinel`), not wrapper
   > names (`ce-ask-security-sentinel`).

   Stop without dispatching anything — partial dispatches confuse the
   merged output.
3. For each validated persona, dispatch in parallel:
   - Read its prompt body from
     `<plugin-root>/references/agent-prompts/<persona>.md`.
   - Spawn an agent with `subagent_type: "general-purpose"`.
   - Prepend a preamble of the form:

     ```
     [ce-persona=<persona> via=ce-ask-panel]

     You are operating as the <persona> specialist. Your role is defined in
     the prompt body above. Honour the manifest's tools/model constraints
     for this role; if a task pulls you toward tools outside that set, stop
     and explain why your role requires it.
     ```

   - Then the user-supplied task context.
4. Wait for all to complete. Merge into a single response, grouping by
   persona with section headers (`## <persona> findings`). Preserve each
   persona's structured output rather than collapsing into prose.

## Notes

- Trace tag `via=ce-ask-panel` distinguishes panel dispatch from direct
  invocation (`via=ce-ask-direct`) when grepping transcripts.
- For one persona, prefer `/ce-ask-<persona-bare-name>` — slightly cheaper
  than going through the panel parser.
- For all-personas-pertinent reviews of code or documents, prefer the
  orchestrator skills (`/ce-code-review`, `/ce-doc-review`) which include
  conditional persona selection logic.
"""


def write_panel(dist: Path, personas: list[Persona]) -> Path:
    skill_dir = dist / "skills" / "ce-ask-panel"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(render_panel(personas), encoding="utf-8")
    return skill_path


META_SKILL_DESCRIPTION = (
    "Discover and dispatch ce-lite specialist personas via a single slash command. "
    "Run with no args to browse the persona catalog (security, architecture, "
    "correctness, simplicity, pattern, performance, data-integrity, doc review, "
    "and more). Run with `<persona-name>` to see one persona's role. Run with "
    "`<persona-name> <task>` to dispatch that specialist on the task. For "
    "tab-complete-friendly invocation use `/ce-ask-<persona>` directly; for "
    "parallel multi-persona dispatch use `/ce-ask-panel`."
)


DEFAULT_HOOK_RULES = {
    "config": {
        "haiku_classifier": {
            "enabled": False,
            "model": "haiku",
            "max_budget_usd": 0.005,
            "timeout_seconds": 8,
            "min_confidence": 0.6,
            "_doc": (
                "Optional Haiku-based intent classifier. When enabled, the "
                "hook falls back to a Haiku call if keyword matching produces "
                "no hit. Haiku reads the user prompt + persona catalog and "
                "returns a structured suggestion. Adds ~1–2s latency per "
                "non-keyword-matching prompt and ~$0.001 quota each. Set "
                "enabled=true to opt in. The keyword path always runs first "
                "(cheap and deterministic); Haiku is the no-keyword "
                "fallback only."
            ),
        }
    },
    "rules": [
        {
            "keywords": [
                "security", "vuln", "vulnerab", "OWASP", "injection", "XSS",
                "CSRF", "SSRF", "auth ", "auth-", "JWT", "OAuth",
                "mass assignment", "sanitiz", "hardcoded secret", "credential leak",
                "open redirect", "deserialization", "is this safe",
                "paranoid review", "is it safe to ship", "before we ship",
            ],
            "persona": "ce-security-sentinel",
            "phrasing": (
                "The prompt looks security-flavored. Consider running "
                "`/ce-lite:ce-ask-security-sentinel` (or invoking the wrapper "
                "via Skill) for a focused security review by a specialist "
                "persona. The wrapper dispatches a sub-agent grounded in "
                "OWASP / injection / authn-authz / secrets-handling expertise."
            ),
        },
        {
            "keywords": [
                "factor out", "extract method", "extract class", "duplicat",
                "copy-pasted", "DRY", "coupling", "abstraction", "boundaries",
                "structural refactor", "service boundaries", "module bound",
                "pattern compliance", "design integrity",
            ],
            "persona": "ce-architecture-strategist",
            "phrasing": (
                "Architecture/design concerns visible. Consider "
                "`/ce-lite:ce-ask-architecture-strategist` for a structural "
                "review (pattern compliance, layer violations, naming "
                "consistency)."
            ),
        },
        {
            "keywords": [
                "YAGNI", "over-engineered", "premature abstraction",
                "redundant abstraction", "simplify", "simpler way",
                "is this too clever", "unnecessary indirection",
                "feels overcomplicated", "could this be simpler",
            ],
            "persona": "ce-code-simplicity-reviewer",
            "phrasing": (
                "Simplicity concerns visible. Consider "
                "`/ce-lite:ce-ask-code-simplicity-reviewer` for a YAGNI/"
                "redundancy review."
            ),
        },
        {
            "keywords": [
                "edge case", "off-by-one", "race condition", "deadlock",
                "concurrency bug", "correctness", "logic bug",
                "is this correct", "boundary condition",
            ],
            "persona": "ce-correctness-reviewer",
            "phrasing": (
                "Correctness concerns visible. Consider "
                "`/ce-lite:ce-ask-correctness-reviewer` for an edge-case / "
                "boundary-condition review."
            ),
        },
        {
            "keywords": [
                "naming consistency", "convention drift", "style consistency",
                "naming pattern", "matches existing", "consistent with",
                "follow the pattern",
            ],
            "persona": "ce-pattern-recognition-specialist",
            "phrasing": (
                "Pattern/consistency review may help. Consider "
                "`/ce-lite:ce-ask-pattern-recognition-specialist` to surface "
                "duplication and convention drift."
            ),
        },
        {
            "keywords": [
                "performance", "latency", "bottleneck", "slow query",
                "N+1", "p99", "throughput", "memory pressure",
            ],
            "persona": "ce-performance-oracle",
            "phrasing": (
                "Performance angle visible. Consider "
                "`/ce-lite:ce-ask-performance-oracle` for a structured "
                "performance review."
            ),
        },
    ]
}


def render_meta_skill() -> str:
    """Render the /ce-ask single-slash-command catalog/dispatch surface.

    Catalog is read from manifest.json at runtime — body stays stable across
    upstream tag bumps even when persona list changes. Per-persona wrappers
    (/ce-ask-<persona>) provide tab-complete-friendly explicit invocation; this
    meta-skill provides the discoverable single-command surface for users who
    don't have a specific persona name in mind yet.
    """
    return f"""\
---
name: ce-ask
description: {json.dumps(META_SKILL_DESCRIPTION)}
argument-hint: "[persona-name [task context]]"
---

{WRAPPER_GENERATED_MARKER}

The single discoverable entry point to ce-lite specialist personas. Three modes
based on argument shape.

## Usage

- `/ce-ask` — print the persona catalog (name + specialty for each).
- `/ce-ask <persona>` — show one persona's full role definition.
- `/ce-ask <persona> <task>` — dispatch that persona on the task.

Persona names are the canonical names from this plugin's persona manifest
(e.g. `ce-security-sentinel`, `ce-architecture-strategist`). Argument
parsing: first whitespace-delimited token is the persona name; everything
after is the task context.

{PROMPT_DISCOVERY_INSTRUCTIONS}

## Steps

1. **No args** — locate the plugin root via discovery instructions above,
   read `<plugin-root>/references/agent-prompts/manifest.json`, and print
   one line per `agents[*]` entry: `<name> — <description>`. Group loosely
   by role family (review, document, design, etc.) if helpful. Stop.

2. **Persona name only** — validate against `manifest.json`. If unknown:
   > Persona `<name>` not in the catalog. Run `/ce-ask` (no args) to see all
   > available personas.
   If known, read `<plugin-root>/references/agent-prompts/<name>.md` and
   present the persona's role definition along with manifest metadata
   (tools, model). Stop.

3. **Persona name + task** — dispatch via the `Agent` tool with
   `subagent_type: "general-purpose"`. Prepend this preamble to the persona's
   prompt body, then append the user's task context:

   ```
   [ce-persona=<persona> via=ce-ask-meta]

   You are operating as the <persona> specialist. Your role is defined in the
   prompt body above. Manifest declares this role uses
   tools=[<tools-from-manifest>] and model=<model>. Honour those constraints:
   if a task pulls you toward tools outside that set, stop and explain why
   your role requires it — don't silently broaden scope.
   ```

## Notes

- Tab-complete-friendly explicit invocation: `/ce-ask-<persona-name>` (one
  per persona, generated alongside this meta-skill).
- Parallel multi-persona dispatch: `/ce-ask-panel <a>,<b>,<c> <task>`.
- Autonomous specialist consultation: the harness invokes the
  `ce-specialist` registered agent directly via `Task` when reviewing
  warrants a specialist perspective; that path doesn't go through this skill.
"""


def write_meta_skill(dist: Path) -> Path:
    skill_dir = dist / "skills" / "ce-ask"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(render_meta_skill(), encoding="utf-8")
    return skill_path


# ---- UserPromptSubmit hook (Phase B.7) ----
#
# Phase B.5's meta-agent (ce-specialist) didn't fire autonomously — the
# integration eval (Phase B.6) measured 0/2 on autonomous review prompts even
# with the agent registered and visible to claude -p. Industry-wide
# research (scottspence.com, paddo.dev, jefflester/claude-skills-supercharged,
# spences10/claude-skills-cli) converges on the same finding: skills/agents
# auto-activate ~20% of the time even with good descriptions, because Claude
# defaults to handling tasks itself rather than delegating to specialists.
#
# The proven workaround is a UserPromptSubmit hook that detects review-flavored
# keywords and injects a suggestion ("consider /ce-ask-<persona>") into the
# prompt before Claude sees it. Measured activation rates jump to 70–84% with
# this approach. Cost is per-matching-prompt (a few hundred tokens of
# injected suggestion), zero at idle — much cheaper than a registered agent
# (~2k always-on) for occasional users.
#
# References:
#   https://scottspence.com/posts/claude-code-skills-dont-auto-activate
#   https://paddo.dev/blog/claude-skills-hooks-solution/
#   https://github.com/anthropics/claude-code/issues/9716


def render_hook_config() -> str:
    """Emit dist/hooks/hooks.json — Claude Code's hook declaration spec."""
    return json.dumps({
        "description": (
            "ce-lite UserPromptSubmit hook: detect review-flavored prompts and "
            "suggest invoking the matching specialist persona wrapper. Pure "
            "keyword matching; no LLM call per prompt; no idle-context cost."
        ),
        "hooks": {
            "UserPromptSubmit": [
                {
                    "hooks": [
                        {
                            "type": "command",
                            "command": "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/auto_suggest.py",
                            "timeout": 5,
                        }
                    ]
                }
            ]
        },
    }, indent=2) + "\n"


def render_hook_rules() -> str:
    """Emit dist/hooks/skill-rules.json — keyword → persona suggestion table.

    This file is the curated extension point. Each release of the converter
    can ship updated default rules; downstream users can override by replacing
    skill-rules.json with their own (any plugin-cache rebuild from upstream
    overwrites it, so persistent customisation should live in a separate
    user-level hook). Keywords are case-insensitive substring matches.
    """
    return json.dumps(DEFAULT_HOOK_RULES, indent=2) + "\n"


def render_hook_script() -> str:
    """Emit dist/hooks/auto_suggest.py — the actual hook implementation.

    Runs once per user prompt. Reads UserPromptSubmit JSON payload from stdin
    (Claude Code hook protocol); matches `prompt` text against
    skill-rules.json keywords (case-insensitive substring); emits an
    `additionalContext` JSON response that gets prepended to Claude's view of
    the prompt. No match → silent exit (zero token cost). At most 3 personas
    suggested per prompt (avoid noise).

    Standard library only — no PyYAML / pyyaml dependency. Fast cold-start
    (~30 ms python overhead + microseconds of matching).
    """
    return '''#!/usr/bin/env python3
"""ce-lite UserPromptSubmit hook — suggest specialist personas based on prompt content.

Generated by ce-lite converter (converter/generate_wrappers.py). Don't edit;
regenerate from `skill-rules.json` instead — this script only loads rules
and config from there at runtime.

Protocol: Claude Code passes the user's prompt as JSON on stdin. If a
suggestion is warranted, we emit `{"hookSpecificOutput": {"hookEventName":
"UserPromptSubmit", "additionalContext": "..."}}` on stdout — that text gets
injected into Claude's view of the prompt as a system reminder before Claude
responds. Silent exit (no stdout) if nothing matches.

Two suggestion strategies:

  1. Keyword matching (default, always runs first). Substring-matches the
     prompt against rule keywords. Cheap, deterministic, no API cost.

  2. Haiku intent classifier (opt-in via config.haiku_classifier.enabled).
     If keyword matching produces no hit AND Haiku is enabled, runs
     `claude -p --model haiku --json-schema` to classify the prompt's intent
     against the persona catalog. ~1-2s latency, ~$0.001 quota per
     no-keyword-match prompt. Per ~/.claude/memory/claude_p_headless_subscription.md
     we use the lightweight invocation pattern (--system-prompt,
     --setting-sources "", CLAUDE_CODE_DISABLE_*).

Reference: https://code.claude.com/docs/en/hooks
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

_GENERATED_BY = "ce-lite converter"

RULES_PATH = Path(__file__).parent / "skill-rules.json"
MAX_SUGGESTIONS = 3  # cap injected text length on prompts that match many rules


def _load_config_and_rules() -> tuple[dict, list[dict]]:
    if not RULES_PATH.is_file():
        return {}, []
    try:
        data = json.loads(RULES_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}, []
    if not isinstance(data, dict):
        return {}, []
    config = data.get("config") if isinstance(data.get("config"), dict) else {}
    rules = data.get("rules") if isinstance(data.get("rules"), list) else []
    return config, rules


def _matches(prompt_lower: str, keywords: list[str]) -> bool:
    return any(
        isinstance(kw, str) and kw.lower() in prompt_lower
        for kw in keywords
    )


def _keyword_suggestions(rules: list[dict], prompt_lower: str) -> list[dict]:
    """Return the matching rules (in declaration order, capped at MAX_SUGGESTIONS)."""
    matched: list[dict] = []
    for rule in rules:
        if not isinstance(rule, dict):
            continue
        keywords = rule.get("keywords") or []
        if _matches(prompt_lower, keywords):
            matched.append(rule)
        if len(matched) >= MAX_SUGGESTIONS:
            break
    return matched


def _haiku_classify(prompt: str, rules: list[dict], cfg: dict) -> dict | None:
    """Optional fallback: run Haiku via `claude -p` to suggest a persona.

    Returns a synthetic rule-shaped dict (with `persona` and `phrasing`) if
    Haiku returns a confident classification. Returns None on any failure
    (network, quota, malformed output, low confidence) — caller treats
    that as "no suggestion."

    Uses the lightweight subscription-quota invocation pattern: minimal
    system prompt, no auto-memory, no settings hierarchy, JSON-schema
    constrained output, hard budget cap. See
    ~/.claude/memory/claude_p_headless_subscription.md.
    """
    if not cfg.get("enabled"):
        return None
    claude_bin = shutil.which("claude")
    if not claude_bin:
        return None

    catalog_lines = []
    for rule in rules:
        if not isinstance(rule, dict):
            continue
        persona = rule.get("persona")
        if persona:
            keywords = rule.get("keywords") or []
            kw_summary = ", ".join(keywords[:6])
            catalog_lines.append(f"- {persona}: {kw_summary}")
    if not catalog_lines:
        return None
    catalog = "\\n".join(catalog_lines)

    system = (
        "You are a routing classifier for ce-lite specialist personas. The "
        "user submitted a prompt to a coding assistant. Decide if any "
        "specialist persona below would substantively improve the response "
        "(by providing focused expertise the main agent might miss). Return "
        "one persona name with a confidence 0.0-1.0, OR null if no "
        "specialist clearly fits.\\n\\nAvailable personas (name: keywords):\\n"
        + catalog
    )
    schema = {
        "type": "object",
        "properties": {
            "persona": {"type": ["string", "null"]},
            "confidence": {"type": "number"},
            "reason": {"type": "string"},
        },
        "required": ["persona", "confidence"],
    }

    cmd = [
        claude_bin, "-p", prompt,
        "--model", str(cfg.get("model", "haiku")),
        "--output-format", "json",
        "--no-session-persistence",
        "--disable-slash-commands",
        "--setting-sources", "",
        "--system-prompt", system,
        "--json-schema", json.dumps(schema),
        "--max-budget-usd", str(cfg.get("max_budget_usd", 0.005)),
    ]
    env = {**os.environ}
    env.pop("CLAUDECODE", None)
    env["CLAUDE_CODE_DISABLE_AUTO_MEMORY"] = "1"
    env["CLAUDE_CODE_DISABLE_CLAUDE_MDS"] = "1"
    env["CLAUDE_CODE_DISABLE_CRON"] = "1"

    timeout_s = float(cfg.get("timeout_seconds", 8))
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, env=env, timeout=timeout_s,
        )
    except (subprocess.TimeoutExpired, OSError):
        return None
    if proc.returncode != 0:
        return None

    try:
        envelope = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return None
    structured = envelope.get("structured_output") if isinstance(envelope, dict) else None
    if not isinstance(structured, dict):
        return None
    persona = structured.get("persona")
    confidence = structured.get("confidence")
    if not persona or not isinstance(confidence, (int, float)):
        return None
    min_conf = float(cfg.get("min_confidence", 0.6))
    if confidence < min_conf:
        return None

    # Map persona back to its rule for the phrasing (preferred — matches the
    # tone of keyword suggestions). Fall back to a synthesized phrasing.
    for rule in rules:
        if isinstance(rule, dict) and rule.get("persona") == persona:
            return rule
    return {
        "persona": persona,
        "phrasing": (
            f"Haiku intent classifier suggests `/ce-lite:ce-ask-{persona[3:]}` "
            f"(confidence {confidence:.2f}): {structured.get('reason', '')}"
        ),
    }


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (OSError, json.JSONDecodeError):
        return 0

    user_prompt = payload.get("prompt") if isinstance(payload, dict) else None
    if not isinstance(user_prompt, str) or not user_prompt.strip():
        return 0

    config, rules = _load_config_and_rules()
    if not rules:
        return 0

    matched = _keyword_suggestions(rules, user_prompt.lower())

    # Fallback: if no keyword match, optionally run Haiku classifier.
    if not matched:
        haiku_cfg = config.get("haiku_classifier", {}) if isinstance(config, dict) else {}
        haiku_match = _haiku_classify(user_prompt, rules, haiku_cfg)
        if haiku_match is not None:
            matched = [haiku_match]

    if not matched:
        return 0

    suggestions = "\\n".join(
        f"- {rule.get('phrasing', '').strip()}"
        for rule in matched[:MAX_SUGGESTIONS]
        if rule.get("phrasing")
    )
    if not suggestions:
        return 0

    response = {
        "hookSpecificOutput": {
            "hookEventName": "UserPromptSubmit",
            "additionalContext": (
                "[ce-lite auto-suggest] Based on the prompt content, ce-lite "
                "specialist personas may be relevant:\\n"
                + suggestions
                + "\\nThese dispatch a sub-agent grounded in the persona's "
                "domain expertise — invoke as a slash command for an "
                "independent specialist perspective. (Suggestions only; the "
                "main agent can also handle the work directly if appropriate.)"
            ),
        }
    }
    json.dump(response, sys.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def write_hooks(dist: Path) -> list[Path]:
    """Emit the hook config + rules + script under dist/hooks/."""
    hooks_dir = dist / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    config_path = hooks_dir / "hooks.json"
    rules_path = hooks_dir / "skill-rules.json"
    script_path = hooks_dir / "auto_suggest.py"

    config_path.write_text(render_hook_config(), encoding="utf-8")
    rules_path.write_text(render_hook_rules(), encoding="utf-8")
    script_path.write_text(render_hook_script(), encoding="utf-8")
    # Make script executable (UserPromptSubmit hook spec uses it as a command)
    script_path.chmod(0o755)
    return [config_path, rules_path, script_path]


def main(dist_arg: str, converter_arg: str | None = None) -> int:
    dist = Path(dist_arg).resolve()
    if not dist.is_dir():
        print(f"generate_wrappers.py: dist not found: {dist}", file=sys.stderr)
        return 2

    converter_dir = (
        Path(converter_arg).resolve() if converter_arg else Path(__file__).resolve().parent
    )

    personas = load_manifest(dist)
    overrides = load_overrides(converter_dir)

    used_overrides = 0
    written: list[Path] = []
    for persona in personas:
        description = overrides.get(persona.name, passA_description(persona.description))
        if persona.name in overrides:
            used_overrides += 1
        written.append(write_wrapper(dist, persona, description))

    panel_path = write_panel(dist, personas)
    meta_skill_path = write_meta_skill(dist)
    hook_paths = write_hooks(dist)

    # Phase B.7: ce-specialist meta-agent removed — Phase B.6 eval measured
    # 0/2 autonomous-routing recall, confirming the industry-known finding
    # that registered subagents auto-fire ~20% of the time. Replaced by a
    # UserPromptSubmit hook (~84% recall, zero idle cost). If a stale
    # dist/agents/ce-specialist.agent.md is around from an earlier run,
    # remove it now so the install is clean.
    stale_agent = dist / "agents" / "ce-specialist.agent.md"
    if stale_agent.exists():
        stale_agent.unlink()
        agents_dir = dist / "agents"
        try:
            agents_dir.rmdir()  # only succeeds if now empty
        except OSError:
            pass

    print(
        f"generate_wrappers.py: wrote {len(written)} wrappers "
        f"({used_overrides} from overrides, {len(written) - used_overrides} via Pass A) "
        f"+ ce-ask-panel + ce-ask discovery skill + UserPromptSubmit hook "
        f"({len(hook_paths)} files)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("dist", help="path to converted plugin dist/ directory")
    parser.add_argument(
        "--converter-dir",
        default=None,
        help="path to converter/ source dir (default: this script's parent)",
    )
    args = parser.parse_args()
    sys.exit(main(args.dist, args.converter_dir))
